In [1]:
import requests
import pandas as pd
from lxml import etree
import json

In [3]:
url='https://movie.douban.com/j/new_search_subjects?sort=U&range=0,10&tags=&start=20&genres=%E5%8A%A8%E7%94%BB'
headers={'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36'}
b='bid=<YOUR_BID>; _vwo_uuid_v2=D59AC51BC0C8DC3659831FEF855201CE9|139d0cb11657fa3ec35701d9b39cb08c; gr_user_id=a3ee981a-7cbd-4f79-abcc-a1bb9c439290; __gads=ID=e29d3a6975f5705b:T=1578526650:S=ALNI_MakJixAUM_fECO5RxxO1OXwECDU9A; ll="118371"; trc_cookie_storage=taboola%2520global%253Auser-id%3D316670c5-974f-4a1d-bca1-b1468f11dac3-tuct4f517ca; __yadk_uid=4qUCa157BbRiORs96PyQmeeXS1lDqYhk; douban-profile-remind=1; __utmz=223695111.1579659800.2.2.utmcsr=baidu|utmccn=(organic)|utmcmd=organic|utmctr=%E8%B1%86%E7%93%A3; douban-fav-remind=1; viewed="3040149_2995812_30199061_4011670_33439842_30253066_26997029"; _ga=GA1.2.1427742213.1578526647; push_noty_num=0; push_doumail_num=0; cto_bundle=kMPNCl9Wbm04bE9yNk1IbFl3MkhLSSUyQlZQSElYc0pWTXMlMkZYTHIlMkIlMkJQaFRBUUNveEVXMkIwTktIMUV1OG1TSU5xczVRSDRHS3JuZ1laOVlwc3ZYTzk3VlR4WVdMeGpNS1hsQ01ORFdzQXBQamYxa0R4cUZIaGhiYUpFR1FVY2s0Q2ROMTRvM1dwMGJhOEFiT0ZadnRuMHZ4MyUyRkpRJTNEJTNE; __utmz=30149280.1589079646.29.19.utmcsr=google|utmccn=(organic)|utmcmd=organic|utmctr=(not%20provided); _pk_ref.100001.4cf6=%5B%22%22%2C%22%22%2C1589097016%2C%22https%3A%2F%2Fwww.baidu.com%2Fs%3Fie%3DUTF-8%26wd%3D%25E8%25B1%2586%25E7%2593%25A3%22%5D; _pk_ses.100001.4cf6=*; __utma=30149280.1427742213.1578526647.1589079646.1589097017.30; __utmc=30149280; __utma=223695111.1692093362.1578813832.1588940662.1589097017.5; __utmb=223695111.0.10.1589097017; __utmc=223695111; ap_v=0,6.0; dbcl2="216584294:NBHisAJp02A"; ck=jzQy; __utmt=1; __utmv=30149280.21658; __utmb=30149280.6.10.1589097017; _pk_id.100001.4cf6=0622253e80c3deb2.1578813831.5.1589097344.1588943550.'
line=b.split(';')
cookie={}
for i in line:
    key,value = i.split('=',1)
    cookie[key] = value

In [4]:
response=requests.get(url,headers=headers,cookies = cookie) 
print(response.status_code)

200

In [5]:
response.encoding = 'utf-8'
html = response.json()  
html

{'data': [{'directors': ['宫崎骏'],
   'rate': '8.6',
   'cover_x': 1067,
   'star': '45',
   'title': '魔女宅急便',
   'url': 'https://movie.douban.com/subject/1307811/',
   'casts': ['高山南', '佐久间玲', '户田惠子', '山口胜平', '信泽三惠子'],
   'cover': 'https://img9.doubanio.com/view/photo/s_ratio_poster/public/p456676352.jpg',
   'id': '1307811',
   'cover_y': 1515},
  {'directors': ['大森贵弘'],
   'rate': '8.9',
   'cover_x': 2142,
   'star': '45',
   'title': '萤火之森',
   'url': 'https://movie.douban.com/subject/5989818/',
   'casts': ['佐仓绫音', '内山昂辉', '辻亲八', '山本兼平', '后藤弘树'],
   'cover': 'https://img9.doubanio.com/view/photo/s_ratio_poster/public/p1675053073.jpg',
   'id': '5989818',
   'cover_y': 3025},
  {'directors': ['宫崎骏'],
   'rate': '8.9',
   'cover_x': 2058,
   'star': '45',
   'title': '幽灵公主',
   'url': 'https://movie.douban.com/subject/1297359/',
   'casts': ['松田洋治', '石田百合子', '田中裕子', '小林薰', '西村雅彦'],
   'cover': 'https://img9.doubanio.com/view/photo/s_ratio_poster/public/p1613191025.jpg',
   'id': '1297359',
   'cover_y': 2907},
  {'directors': ['彼特·道格特', '大卫·斯沃曼', '李·昂克里奇'],
   'rate': '8.7',
   'cover_x': 1277,
   'star': '45',
   'title': '怪兽电力公司',
   'url': 'https://movie.douban.com/subject/1291579/',
   'casts': ['约翰·古德曼', '比利·克里斯托', '玛丽·吉布斯', '史蒂夫·布西密', '詹姆斯·柯本'],
   'cover': 'https://img9.doubanio.com/view/photo/s_ratio_poster/public/p2513247938.jpg',
   'id': '1291579',
   'cover_y': 1897},
  {'directors': ['宫崎骏'],
   'rate': '8.5',
   'cover_x': 1065,
   'star': '45',
   'title': '悬崖上的金鱼姬',
   'url': 'https://movie.douban.com/subject/1959877/',
   'casts': ['奈良柚莉爱', '土井洋辉', '山口智子', '长岛一茂', '天海祐希'],
   'cover': 'https://img9.doubanio.com/view/photo/s_ratio_poster/public/p454118602.jpg',
   'id': '1959877',
   'cover_y': 1510},
  {'directors': ['卡洛斯·沙尔丹哈', '克里斯·韦奇'],
   'rate': '8.6',
   'cover_x': 672,
   'star': '45',
   'title': '冰川时代',
   'url': 'https://movie.douban.com/subject/1291578/',
   'casts': ['雷·罗马诺', '约翰·雷吉扎莫', '丹尼斯·利瑞', '杰克·布莱克', '克里斯·韦奇'],
   'cover': 'https://img9.doubanio.com/view/photo/s_ratio_poster/public/p1910895719.jpg',
   'id': '1291578',
   'cover_y': 964},
  {'directors': ['木头', '皇贞季', '顾杰'],
   'rate': '8.2',
   'cover_x': 2000,
   'star': '40',
   'title': '罗小黑战记',
   'url': 'https://movie.douban.com/subject/26709258/',
   'casts': ['山新', '郝祥海', '刘明月'],
   'cover': 'https://img9.doubanio.com/view/photo/s_ratio_poster/public/p2568288336.jpg',
   'id': '26709258',
   'cover_y': 3208},
  {'directors': ['万籁鸣', '唐澄'],
   'rate': '9.3',
   'cover_x': 800,
   'star': '45',
   'title': '大闹天宫',
   'url': 'https://movie.douban.com/subject/1418019/',
   'casts': ['邱岳峰', '富润生', '毕克', '尚华', '于鼎'],
   'cover': 'https://img9.doubanio.com/view/photo/s_ratio_poster/public/p2184505167.jpg',
   'id': '1418019',
   'cover_y': 1094},
  {'directors': ['克里斯·巴克', '珍妮弗·李'],
   'rate': '7.2',
   'cover_x': 1080,
   'star': '35',
   'title': '冰雪奇缘2',
   'url': 'https://movie.douban.com/subject/25887288/',
   'casts': ['克里斯汀·贝尔', '伊迪娜·门泽尔', '乔什·加德', '乔纳森·格罗夫', '杰森·雷特'],
   'cover': 'https://img9.doubanio.com/view/photo/s_ratio_poster/public/p2572847101.jpg',
   'id': '25887288',
   'cover_y': 1543},
  {'directors': ['彼特·道格特', '罗纳尔多·德尔·卡门'],
   'rate': '8.7',
   'cover_x': 1986,
   'star': '45',
   'title': '头脑特工队',
   'url': 'https://movie.douban.com/subject/10533913/',
   'casts': ['艾米·波勒', '菲利丝·史密斯', '理查德·坎德', '比尔·哈德尔', '刘易斯·布莱克'],
   'cover': 'https://img9.doubanio.com/view/photo/s_ratio_poster/public/p2266293606.jpg',
   'id': '10533913',
   'cover_y': 2835},
  {'directors': ['宫崎骏'],
   'rate': '8.1',
   'cover_x': 1024,
   'star': '40',
   'title': '起风了',
   'url': 'https://movie.douban.com/subject/6791750/',
   'casts': ['庵野秀明', '泷本美织', '西岛秀俊', '西村雅彦', '史蒂夫·阿尔珀特'],
   'cover': 'https://img9.doubanio.com/view/photo/s_ratio_poster/public/p1998028598.jpg',
   'id': '6791750',
   'cover_y': 1446},
  {'directors': ['李·昂克里奇'],
   'rate': '8.8',
   'cover_x': 1013,
   'star': '45',
   'title': '玩具总动员3',
   'url': 'https://movie.douban.com/subject/1858711/',
   'casts': ['汤姆·汉克斯', '蒂姆·艾伦', '琼·库萨克', '尼德·巴蒂', '唐·里克斯'],
   'cover': 'https://img9.doubanio.com/view/photo/s_ratio_poster/public/p1283675359.jpg',
   'id': '1858711',
   'cover_y': 1500},
  {'directors': ['乔恩·费儒'],
   'rate': '7.4',
   'cover_x': 2500,
   'star': '35',
   'title': '狮子王',
   'url': 'https://movie.douban.com/subject/26884354/',
   'casts': ['唐纳德·格洛弗', '阿尔法·伍达德', '詹姆斯·厄尔·琼斯', '切瓦特·埃加福', '科甘-迈克尔·凯'],
   'cover': 'https://img9.doubanio.com/view/photo/s_ratio_poster/public/p2559742751.jpg',
   'id': '26884354',
   'cover_y': 3571},
  {'directors': ['米林宏昌'],
   'rate': '8.8',
   'cover_x': 2142,
   'star': '45',
   'title': '借东西的小人阿莉埃蒂',
   'url': 'https://movie.douban.com/subject/4202302/',
   'casts': ['志田未来', '神木隆之介', '树木希林', '三浦友和', '大竹忍'],
   'cover': 'https://img9.doubanio.com/view/photo/s_ratio_poster/public/p617533616.jpg',
   'id': '4202302',
   'cover_y': 3025},
  {'directors': ['鲍勃·佩尔西凯蒂', '彼得·拉姆齐', '罗德尼·罗斯曼'],
   'rate': '8.6',
   'cover_x': 2200,
   'star': '45',
   'title': '蜘蛛侠：平行宇宙',
   'url': 'https://movie.douban.com/subject/26374197/',
   'casts': ['沙梅克·摩尔', '杰克·约翰逊', '海莉·斯坦菲尔德', '马赫沙拉·阿里', '布莱恩·泰里·亨利'],
   'cover': 'https://img9.doubanio.com/view/photo/s_ratio_poster/public/p2542867516.jpg',
   'id': '26374197',
   'cover_y': 3123},
  {'directors': ['瑞奇·摩尔'],
   'rate': '8.7',
   'cover_x': 770,
   'star': '45',
   'title': '无敌破坏王',
   'url': 'https://movie.douban.com/subject/6534248/',
   'casts': ['约翰·C·赖利', '萨拉·西尔弗曼', '杰克·麦克布瑞尔', '简·林奇', '艾伦·图代克'],
   'cover': 'https://img9.doubanio.com/view/photo/s_ratio_poster/public/p1735642656.jpg',
   'id': '6534248',
   'cover_y': 1100},
  {'directors': ['宫崎骏'],
   'rate': '8.9',
   'cover_x': 1788,
   'star': '45',
   'title': '风之谷',
   'url': 'https://movie.douban.com/subject/1291585/',
   'casts': ['岛本须美', '松田洋治', '榊原良子', '辻村真人', '京田尚子'],
   'cover': 'https://img9.doubanio.com/view/photo/s_ratio_poster/public/p1917567652.jpg',
   'id': '1291585',
   'cover_y': 2531},
  {'directors': ['皮埃尔·柯芬', '克里斯·雷纳德'],
   'rate': '8.0',
   'cover_x': 5001,
   'star': '40',
   'title': '神偷奶爸2',
   'url': 'https://movie.douban.com/subject/4915857/',
   'casts': ['史蒂夫·卡瑞尔', '克里斯汀·韦格', '本杰明·布拉特', '米兰达·卡斯格拉夫', '拉塞尔·布兰德'],
   'cover': 'https://img9.doubanio.com/view/photo/s_ratio_poster/public/p2164225595.jpg',
   'id': '4915857',
   'cover_y': 7000},
  {'directors': ['马克·奥斯本', '约翰·斯蒂文森'],
   'rate': '8.1',
   'cover_x': 1100,
   'star': '40',
   'title': '功夫熊猫',
   'url': 'https://movie.douban.com/subject/1783457/',
   'casts': ['杰克·布莱克', '达斯汀·霍夫曼', '安吉丽娜·朱莉', '伊恩·麦柯肖恩', '成龙'],
   'cover': 'https://img9.doubanio.com/view/photo/s_ratio_poster/public/p1597238857.jpg',
   'id': '1783457',
   'cover_y': 1634},
  {'directors': ['乔什·库雷'],
   'rate': '8.6',
   'cover_x': 1968,
   'star': '45',
   'title': '玩具总动员4',
   'url': 'https://movie.douban.com/subject/6850547/',
   'casts': ['汤姆·汉克斯', '蒂姆·艾伦', '安妮·波茨', '托尼·海尔', '科甘-迈克尔·凯'],
   'cover': 'https://img9.doubanio.com/view/photo/s_ratio_poster/public/p2557284230.jpg',
   'id': '6850547',
   'cover_y': 2780}]}

In [6]:
html1=html['data']
print(html1)

[{'directors': ['宫崎骏'], 'rate': '8.6', 'cover_x': 1067, 'star': '45', 'title': '魔女宅急便', 'url': 'https://movie.douban.com/subject/1307811/', 'casts': ['高山南', '佐久间玲', '户田惠子', '山口胜平', '信泽三惠子'], 'cover': 'https://img9.doubanio.com/view/photo/s_ratio_poster/public/p456676352.jpg', 'id': '1307811', 'cover_y': 1515}, {'directors': ['大森贵弘'], 'rate': '8.9', 'cover_x': 2142, 'star': '45', 'title': '萤火之森', 'url': 'https://movie.douban.com/subject/5989818/', 'casts': ['佐仓绫音', '内山昂辉', '辻亲八', '山本兼平', '后藤弘树'], 'cover': 'https://img9.doubanio.com/view/photo/s_ratio_poster/public/p1675053073.jpg', 'id': '5989818', 'cover_y': 3025}, {'directors': ['宫崎骏'], 'rate': '8.9', 'cover_x': 2058, 'star': '45', 'title': '幽灵公主', 'url': 'https://movie.douban.com/subject/1297359/', 'casts': ['松田洋治', '石田百合子', '田中裕子', '小林薰', '西村雅彦'], 'cover': 'https://img9.doubanio.com/view/photo/s_ratio_poster/public/p1613191025.jpg', 'id': '1297359', 'cover_y': 2907}, {'directors': ['彼特·道格特', '大卫·斯沃曼', '李·昂克里奇'], 'rate': '8.7', 'cover_x': 1277, 'star': '45', 'title': '怪兽电力公司', 'url': 'https://movie.douban.com/subject/1291579/', 'casts': ['约翰·古德曼', '比利·克里斯托', '玛丽·吉布斯', '史蒂夫·布西密', '詹姆斯·柯本'], 'cover': 'https://img9.doubanio.com/view/photo/s_ratio_poster/public/p2513247938.jpg', 'id': '1291579', 'cover_y': 1897}, {'directors': ['宫崎骏'], 'rate': '8.5', 'cover_x': 1065, 'star': '45', 'title': '悬崖上的金鱼姬', 'url': 'https://movie.douban.com/subject/1959877/', 'casts': ['奈良柚莉爱', '土井洋辉', '山口智子', '长岛一茂', '天海祐希'], 'cover': 'https://img9.doubanio.com/view/photo/s_ratio_poster/public/p454118602.jpg', 'id': '1959877', 'cover_y': 1510}, {'directors': ['卡洛斯·沙尔丹哈', '克里斯·韦奇'], 'rate': '8.6', 'cover_x': 672, 'star': '45', 'title': '冰川时代', 'url': 'https://movie.douban.com/subject/1291578/', 'casts': ['雷·罗马诺', '约翰·雷吉扎莫', '丹尼斯·利瑞', '杰克·布莱克', '克里斯·韦奇'], 'cover': 'https://img9.doubanio.com/view/photo/s_ratio_poster/public/p1910895719.jpg', 'id': '1291578', 'cover_y': 964}, {'directors': ['木头', '皇贞季', '顾杰'], 'rate': '8.2', 'cover_x': 2000, 'star': '40', 'title': '罗小黑战记', 'url': 'https://movie.douban.com/subject/26709258/', 'casts': ['山新', '郝祥海', '刘明月'], 'cover': 'https://img9.doubanio.com/view/photo/s_ratio_poster/public/p2568288336.jpg', 'id': '26709258', 'cover_y': 3208}, {'directors': ['万籁鸣', '唐澄'], 'rate': '9.3', 'cover_x': 800, 'star': '45', 'title': '大闹天宫', 'url': 'https://movie.douban.com/subject/1418019/', 'casts': ['邱岳峰', '富润生', '毕克', '尚华', '于鼎'], 'cover': 'https://img9.doubanio.com/view/photo/s_ratio_poster/public/p2184505167.jpg', 'id': '1418019', 'cover_y': 1094}, {'directors': ['克里斯·巴克', '珍妮弗·李'], 'rate': '7.2', 'cover_x': 1080, 'star': '35', 'title': '冰雪奇缘2', 'url': 'https://movie.douban.com/subject/25887288/', 'casts': ['克里斯汀·贝尔', '伊迪娜·门泽尔', '乔什·加德', '乔纳森·格罗夫', '杰森·雷特'], 'cover': 'https://img9.doubanio.com/view/photo/s_ratio_poster/public/p2572847101.jpg', 'id': '25887288', 'cover_y': 1543}, {'directors': ['彼特·道格特', '罗纳尔多·德尔·卡门'], 'rate': '8.7', 'cover_x': 1986, 'star': '45', 'title': '头脑特工队', 'url': 'https://movie.douban.com/subject/10533913/', 'casts': ['艾米·波勒', '菲利丝·史密斯', '理查德·坎德', '比尔·哈德尔', '刘易斯·布莱克'], 'cover': 'https://img9.doubanio.com/view/photo/s_ratio_poster/public/p2266293606.jpg', 'id': '10533913', 'cover_y': 2835}, {'directors': ['宫崎骏'], 'rate': '8.1', 'cover_x': 1024, 'star': '40', 'title': '起风了', 'url': 'https://movie.douban.com/subject/6791750/', 'casts': ['庵野秀明', '泷本美织', '西岛秀俊', '西村雅彦', '史蒂夫·阿尔珀特'], 'cover': 'https://img9.doubanio.com/view/photo/s_ratio_poster/public/p1998028598.jpg', 'id': '6791750', 'cover_y': 1446}, {'directors': ['李·昂克里奇'], 'rate': '8.8', 'cover_x': 1013, 'star': '45', 'title': '玩具总动员3', 'url': 'https://movie.douban.com/subject/1858711/', 'casts': ['汤姆·汉克斯', '蒂姆·艾伦', '琼·库萨克', '尼德·巴蒂', '唐·里克斯'], 'cover': 'https://img9.doubanio.com/view/photo/s_ratio_poster/public/p1283675359.jpg', 'id': '1858711', 'cover_y': 1500}, {'directors': ['乔恩·费儒'], 'rate': '7.4', 'cover_x': 2500, 'star': '35', 'title': '狮子王', 'url': 'https://movie.douban.com/subject/26884354/', 'casts': ['唐纳德·格洛弗', '阿尔法·伍达德', '詹姆斯·厄尔·琼斯', '切瓦特·埃加福', '科甘-迈克尔·凯'], 'cover': 'https://img9.doubanio.com/view/photo/s_ratio_poster/public/p2559742751.jpg', 'id': '26884354', 'cover_y': 3571}, {'directors': ['米林宏昌'], 'rate': '8.8', 'cover_x': 2142, 'star': '45', 'title': '借东西的小人阿莉埃蒂', 'url': 'https://movie.douban.com/subject/4202302/', 'casts': ['志田未来', '神木隆之介', '树木希林', '三浦友和', '大竹忍'], 'cover': 'https://img9.doubanio.com/view/photo/s_ratio_poster/public/p617533616.jpg', 'id': '4202302', 'cover_y': 3025}, {'directors': ['鲍勃·佩尔西凯蒂', '彼得·拉姆齐', '罗德尼·罗斯曼'], 'rate': '8.6', 'cover_x': 2200, 'star': '45', 'title': '蜘蛛侠：平行宇宙', 'url': 'https://movie.douban.com/subject/26374197/', 'casts': ['沙梅克·摩尔', '杰克·约翰逊', '海莉·斯坦菲尔德', '马赫沙拉·阿里', '布莱恩·泰里·亨利'], 'cover': 'https://img9.doubanio.com/view/photo/s_ratio_poster/public/p2542867516.jpg', 'id': '26374197', 'cover_y': 3123}, {'directors': ['瑞奇·摩尔'], 'rate': '8.7', 'cover_x': 770, 'star': '45', 'title': '无敌破坏王', 'url': 'https://movie.douban.com/subject/6534248/', 'casts': ['约翰·C·赖利', '萨拉·西尔弗曼', '杰克·麦克布瑞尔', '简·林奇', '艾伦·图代克'], 'cover': 'https://img9.doubanio.com/view/photo/s_ratio_poster/public/p1735642656.jpg', 'id': '6534248', 'cover_y': 1100}, {'directors': ['宫崎骏'], 'rate': '8.9', 'cover_x': 1788, 'star': '45', 'title': '风之谷', 'url': 'https://movie.douban.com/subject/1291585/', 'casts': ['岛本须美', '松田洋治', '榊原良子', '辻村真人', '京田尚子'], 'cover': 'https://img9.doubanio.com/view/photo/s_ratio_poster/public/p1917567652.jpg', 'id': '1291585', 'cover_y': 2531}, {'directors': ['皮埃尔·柯芬', '克里斯·雷纳德'], 'rate': '8.0', 'cover_x': 5001, 'star': '40', 'title': '神偷奶爸2', 'url': 'https://movie.douban.com/subject/4915857/', 'casts': ['史蒂夫·卡瑞尔', '克里斯汀·韦格', '本杰明·布拉特', '米兰达·卡斯格拉夫', '拉塞尔·布兰德'], 'cover': 'https://img9.doubanio.com/view/photo/s_ratio_poster/public/p2164225595.jpg', 'id': '4915857', 'cover_y': 7000}, {'directors': ['马克·奥斯本', '约翰·斯蒂文森'], 'rate': '8.1', 'cover_x': 1100, 'star': '40', 'title': '功夫熊猫', 'url': 'https://movie.douban.com/subject/1783457/', 'casts': ['杰克·布莱克', '达斯汀·霍夫曼', '安吉丽娜·朱莉', '伊恩·麦柯肖恩', '成龙'], 'cover': 'https://img9.doubanio.com/view/photo/s_ratio_poster/public/p1597238857.jpg', 'id': '1783457', 'cover_y': 1634}, {'directors': ['乔什·库雷'], 'rate': '8.6', 'cover_x': 1968, 'star': '45', 'title': '玩具总动员4', 'url': 'https://movie.douban.com/subject/6850547/', 'casts': ['汤姆·汉克斯', '蒂姆·艾伦', '安妮·波茨', '托尼·海尔', '科甘-迈克尔·凯'], 'cover': 'https://img9.doubanio.com/view/photo/s_ratio_poster/public/p2557284230.jpg', 'id': '6850547', 'cover_y': 2780}]

In [7]:
directors=[]
rate=[]
star=[]
url=[]
title=[]
cover=[]
id=[]
casts=[]
cover_x=[]
for one in html1:
    directors.append(one['directors'])
    rate.append(one['rate'])
    star.append(one['star'])
    url.append(one['url'])
    cover.append(one['cover'])
    title.append(one['title'])
    id.append(one['id'])
    casts.append(one['casts'])
    cover_x.append(one['cover_x'])

In [8]:
columns={'导演':directors,'剧名':title,'演员':casts,'评分':rate,'星星':star,'评价':cover_x,'url':url,'图片':cover,'id':id}

In [9]:
data=pd.DataFrame(columns)
data.shape
data

,导演,剧名,演员,评分,星星,评价,url,图片,id
0,[宫崎骏],魔女宅急便,"[高山南, 佐久间玲, 户田惠子, 山口胜平, 信泽三惠子]",8.6,45,1067,https://movie.douban.com/subject/1307811/,https://img9.doubanio.com/view/photo/s_ratio_p...,1307811
1,[大森贵弘],萤火之森,"[佐仓绫音, 内山昂辉, 辻亲八, 山本兼平, 后藤弘树]",8.9,45,2142,https://movie.douban.com/subject/5989818/,https://img9.doubanio.com/view/photo/s_ratio_p...,5989818
2,[宫崎骏],幽灵公主,"[松田洋治, 石田百合子, 田中裕子, 小林薰, 西村雅彦]",8.9,45,2058,https://movie.douban.com/subject/1297359/,https://img9.doubanio.com/view/photo/s_ratio_p...,1297359
3,"[彼特·道格特, 大卫·斯沃曼, 李·昂克里奇]",怪兽电力公司,"[约翰·古德曼, 比利·克里斯托, 玛丽·吉布斯, 史蒂夫·布西密, 詹姆斯·柯本]",8.7,45,1277,https://movie.douban.com/subject/1291579/,https://img9.doubanio.com/view/photo/s_ratio_p...,1291579
4,[宫崎骏],悬崖上的金鱼姬,"[奈良柚莉爱, 土井洋辉, 山口智子, 长岛一茂, 天海祐希]",8.5,45,1065,https://movie.douban.com/subject/1959877/,https://img9.doubanio.com/view/photo/s_ratio_p...,1959877
5,"[卡洛斯·沙尔丹哈, 克里斯·韦奇]",冰川时代,"[雷·罗马诺, 约翰·雷吉扎莫, 丹尼斯·利瑞, 杰克·布莱克, 克里斯·韦奇]",8.6,45,672,https://movie.douban.com/subject/1291578/,https://img9.doubanio.com/view/photo/s_ratio_p...,1291578
6,"[木头, 皇贞季, 顾杰]",罗小黑战记,"[山新, 郝祥海, 刘明月]",8.2,40,2000,https://movie.douban.com/subject/26709258/,https://img9.doubanio.com/view/photo/s_ratio_p...,26709258
7,"[万籁鸣, 唐澄]",大闹天宫,"[邱岳峰, 富润生, 毕克, 尚华, 于鼎]",9.3,45,800,https://movie.douban.com/subject/1418019/,https://img9.doubanio.com/view/photo/s_ratio_p...,1418019
8,"[克里斯·巴克, 珍妮弗·李]",冰雪奇缘2,"[克里斯汀·贝尔, 伊迪娜·门泽尔, 乔什·加德, 乔纳森·格罗夫, 杰森·雷特]",7.2,35,1080,https://movie.douban.com/subject/25887288/,https://img9.doubanio.com/view/photo/s_ratio_p...,25887288
9,"[彼特·道格特, 罗纳尔多·德尔·卡门]",头脑特工队,"[艾米·波勒, 菲利丝·史密斯, 理查德·坎德, 比尔·哈德尔, 刘易斯·布莱克]",8.7,45,1986,https://movie.douban.com/subject/10533913/,https://img9.doubanio.com/view/photo/s_ratio_p...,10533913
10,[宫崎骏],起风了,"[庵野秀明, 泷本美织, 西岛秀俊, 西村雅彦, 史蒂夫·阿尔珀特]",8.1,40,1024,https://movie.douban.com/subject/6791750/,https://img9.doubanio.com/view/photo/s_ratio_p...,6791750
11,[李·昂克里奇],玩具总动员3,"[汤姆·汉克斯, 蒂姆·艾伦, 琼·库萨克, 尼德·巴蒂, 唐·里克斯]",8.8,45,1013,https://movie.douban.com/subject/1858711/,https://img9.doubanio.com/view/photo/s_ratio_p...,1858711
12,[乔恩·费儒],狮子王,"[唐纳德·格洛弗, 阿尔法·伍达德, 詹姆斯·厄尔·琼斯, 切瓦特·埃加福, 科甘-迈克尔·凯]",7.4,35,2500,https://movie.douban.com/subject/26884354/,https://img9.doubanio.com/view/photo/s_ratio_p...,26884354
13,[米林宏昌],借东西的小人阿莉埃蒂,"[志田未来, 神木隆之介, 树木希林, 三浦友和, 大竹忍]",8.8,45,2142,https://movie.douban.com/subject/4202302/,https://img9.doubanio.com/view/photo/s_ratio_p...,4202302
14,"[鲍勃·佩尔西凯蒂, 彼得·拉姆齐, 罗德尼·罗斯曼]",蜘蛛侠：平行宇宙,"[沙梅克·摩尔, 杰克·约翰逊, 海莉·斯坦菲尔德, 马赫沙拉·阿里, 布莱恩·泰里·亨利]",8.6,45,2200,https://movie.douban.com/subject/26374197/,https://img9.doubanio.com/view/photo/s_ratio_p...,26374197
15,[瑞奇·摩尔],无敌破坏王,"[约翰·C·赖利, 萨拉·西尔弗曼, 杰克·麦克布瑞尔, 简·林奇, 艾伦·图代克]",8.7,45,770,https://movie.douban.com/subject/6534248/,https://img9.doubanio.com/view/photo/s_ratio_p...,6534248
16,[宫崎骏],风之谷,"[岛本须美, 松田洋治, 榊原良子, 辻村真人, 京田尚子]",8.9,45,1788,https://movie.douban.com/subject/1291585/,https://img9.doubanio.com/view/photo/s_ratio_p...,1291585
17,"[皮埃尔·柯芬, 克里斯·雷纳德]",神偷奶爸2,"[史蒂夫·卡瑞尔, 克里斯汀·韦格, 本杰明·布拉特, 米兰达·卡斯格拉夫, 拉塞尔·布兰德]",8.0,40,5001,https://movie.douban.com/subject/4915857/,https://img9.doubanio.com/view/photo/s_ratio_p...,4915857
18,"[马克·奥斯本, 约翰·斯蒂文森]",功夫熊猫,"[杰克·布莱克, 达斯汀·霍夫曼, 安吉丽娜·朱莉, 伊恩·麦柯肖恩, 成龙]",8.1,40,1100,https://movie.douban.com/subject/1783457/,https://img9.doubanio.com/view/photo/s_ratio_p...,1783457
19,[乔什·库雷],玩具总动员4,"[汤姆·汉克斯, 蒂姆·艾伦, 安妮·波茨, 托尼·海尔, 科甘-迈克尔·凯]",8.6,45,1968,https://movie.douban.com/subject/6850547/,https://img9.doubanio.com/view/photo/s_ratio_p...,6850547

In [12]:
title=[]
juqing=[]
for i in range(len(data['url'])):
    res=requests.get(data['url'][i],headers=headers)
    html = etree.HTML(res.text)
    title.append(''.join(html.xpath('//*[@id="content"]/h1/span[1]/text()')))
    juqing.append(''.join(html.xpath('//*[@id="link-report"]//span[@property="v:summary"]/text()')))

In [13]:
col={'剧名':title,'剧情':juqing}
df2=pd.DataFrame(col)
df2.head()

                      剧名                                                 剧情
0           魔女宅急便 魔女の宅急便  \n                                　　琪琪今年13岁了，按...
1             萤火之森 蛍火の杜へ  \n                                　　某年夏天，6岁小女孩...
2             幽灵公主 もののけ姫  \n                                　　为了拯救危难中的村民...
3  怪兽电力公司 Monsters, Inc.  \n                                    　　我们不知道，...
4        悬崖上的金鱼姬 崖の上のポニョ  \n                                　　金鱼姬是一条活泼好动...

In [14]:
da2=pd.concat([data,df2],axis=1)
da2

,导演,剧名,演员,评分,星星,评价,url,图片,id,剧名,剧情
0,[宫崎骏],魔女宅急便,"[高山南, 佐久间玲, 户田惠子, 山口胜平, 信泽三惠子]",8.6,45,1067,https://movie.douban.com/subject/1307811/,https://img9.doubanio.com/view/photo/s_ratio_p...,1307811,魔女宅急便 魔女の宅急便,\n 琪琪今年13岁了，按...
1,[大森贵弘],萤火之森,"[佐仓绫音, 内山昂辉, 辻亲八, 山本兼平, 后藤弘树]",8.9,45,2142,https://movie.douban.com/subject/5989818/,https://img9.doubanio.com/view/photo/s_ratio_p...,5989818,萤火之森 蛍火の杜へ,\n 某年夏天，6岁小女孩...
2,[宫崎骏],幽灵公主,"[松田洋治, 石田百合子, 田中裕子, 小林薰, 西村雅彦]",8.9,45,2058,https://movie.douban.com/subject/1297359/,https://img9.doubanio.com/view/photo/s_ratio_p...,1297359,幽灵公主 もののけ姫,\n 为了拯救危难中的村民...
3,"[彼特·道格特, 大卫·斯沃曼, 李·昂克里奇]",怪兽电力公司,"[约翰·古德曼, 比利·克里斯托, 玛丽·吉布斯, 史蒂夫·布西密, 詹姆斯·柯本]",8.7,45,1277,https://movie.douban.com/subject/1291579/,https://img9.doubanio.com/view/photo/s_ratio_p...,1291579,"怪兽电力公司 Monsters, Inc.",\n 我们不知道，...
4,[宫崎骏],悬崖上的金鱼姬,"[奈良柚莉爱, 土井洋辉, 山口智子, 长岛一茂, 天海祐希]",8.5,45,1065,https://movie.douban.com/subject/1959877/,https://img9.doubanio.com/view/photo/s_ratio_p...,1959877,悬崖上的金鱼姬 崖の上のポニョ,\n 金鱼姬是一条活泼好动...
5,"[卡洛斯·沙尔丹哈, 克里斯·韦奇]",冰川时代,"[雷·罗马诺, 约翰·雷吉扎莫, 丹尼斯·利瑞, 杰克·布莱克, 克里斯·韦奇]",8.6,45,672,https://movie.douban.com/subject/1291578/,https://img9.doubanio.com/view/photo/s_ratio_p...,1291578,冰川时代 Ice Age,\n 冰河时期降至，动物们...
6,"[木头, 皇贞季, 顾杰]",罗小黑战记,"[山新, 郝祥海, 刘明月]",8.2,40,2000,https://movie.douban.com/subject/26709258/,https://img9.doubanio.com/view/photo/s_ratio_p...,26709258,罗小黑战记,\n 在熙攘的人类世界里，...
7,"[万籁鸣, 唐澄]",大闹天宫,"[邱岳峰, 富润生, 毕克, 尚华, 于鼎]",9.3,45,800,https://movie.douban.com/subject/1418019/,https://img9.doubanio.com/view/photo/s_ratio_p...,1418019,大闹天宫,\n 话说在东土傲来国有一...
8,"[克里斯·巴克, 珍妮弗·李]",冰雪奇缘2,"[克里斯汀·贝尔, 伊迪娜·门泽尔, 乔什·加德, 乔纳森·格罗夫, 杰森·雷特]",7.2,35,1080,https://movie.douban.com/subject/25887288/,https://img9.doubanio.com/view/photo/s_ratio_p...,25887288,冰雪奇缘2 Frozen II,\n 历经严酷考验，阿伦戴...
9,"[彼特·道格特, 罗纳尔多·德尔·卡门]",头脑特工队,"[艾米·波勒, 菲利丝·史密斯, 理查德·坎德, 比尔·哈德尔, 刘易斯·布莱克]",8.7,45,1986,https://movie.douban.com/subject/10533913/,https://img9.doubanio.com/view/photo/s_ratio_p...,10533913,头脑特工队 Inside Out,\n 可爱的小女孩莱莉（凯...
10,[宫崎骏],起风了,"[庵野秀明, 泷本美织, 西岛秀俊, 西村雅彦, 史蒂夫·阿尔珀特]",8.1,40,1024,https://movie.douban.com/subject/6791750/,https://img9.doubanio.com/view/photo/s_ratio_p...,6791750,起风了 風立ちぬ,\n 那是一个动荡的年代，...
11,[李·昂克里奇],玩具总动员3,"[汤姆·汉克斯, 蒂姆·艾伦, 琼·库萨克, 尼德·巴蒂, 唐·里克斯]",8.8,45,1013,https://movie.douban.com/subject/1858711/,https://img9.doubanio.com/view/photo/s_ratio_p...,1858711,玩具总动员3 Toy Story 3,\n 距上一次的冒险已经过...
12,[乔恩·费儒],狮子王,"[唐纳德·格洛弗, 阿尔法·伍达德, 詹姆斯·厄尔·琼斯, 切瓦特·埃加福, 科甘-迈克尔·凯]",7.4,35,2500,https://movie.douban.com/subject/26884354/,https://img9.doubanio.com/view/photo/s_ratio_p...,26884354,狮子王 The Lion King,\n 广袤无垠的非洲大草原...
13,[米林宏昌],借东西的小人阿莉埃蒂,"[志田未来, 神木隆之介, 树木希林, 三浦友和, 大竹忍]",8.8,45,2142,https://movie.douban.com/subject/4202302/,https://img9.doubanio.com/view/photo/s_ratio_p...,4202302,借东西的小人阿莉埃蒂 借りぐらしのアリエッティ,\n 虽然患有心脏方面的疾...
14,"[鲍勃·佩尔西凯蒂, 彼得·拉姆齐, 罗德尼·罗斯曼]",蜘蛛侠：平行宇宙,"[沙梅克·摩尔, 杰克·约翰逊, 海莉·斯坦菲尔德, 马赫沙拉·阿里, 布莱恩·泰里·亨利]",8.6,45,2200,https://movie.douban.com/subject/26374197/,https://img9.doubanio.com/view/photo/s_ratio_p...,26374197,蜘蛛侠：平行宇宙 Spider-Man: Into the Spider-Verse,\n 正就读中学的少年迈尔...
15,[瑞奇·摩尔],无敌破坏王,"[约翰·C·赖利, 萨拉·西尔弗曼, 杰克·麦克布瑞尔, 简·林奇, 艾伦·图代克]",8.7,45,770,https://movie.douban.com/subject/6534248/,https://img9.doubanio.com/view/photo/s_ratio_p...,6534248,无敌破坏王 Wreck-It Ralph,\n 无敌破坏王（...
16,[宫崎骏],风之谷,"[岛本须美, 松田洋治, 榊原良子, 辻村真人, 京田尚子]",8.9,45,1788,https://movie.douban.com/subject/1291585/,https://img9.doubanio.com/view/photo/s_ratio_p...,1291585,风之谷 風の谷のナウシカ,\n 工业文明的高度发展，...
17,"[皮埃尔·柯芬, 克里斯·雷纳德]",神偷奶爸2,"[史蒂夫·卡瑞尔, 克里斯汀·韦格, 本杰明·布拉特, 米兰达·卡斯格拉夫, 拉塞尔·布兰德]",8.0,40,5001,https://movie.douban.com/subject/4915857/,https://img9.doubanio.com/view/photo/s_ratio_p...,4915857,神偷奶爸2 Despicable Me 2,\n 自从与玛戈（...
18,"[马克·奥斯本, 约翰·斯蒂文森]",功夫熊猫,"[杰克·布莱克, 达斯汀·霍夫曼, 安吉丽娜·朱莉, 伊恩·麦柯肖恩, 成龙]",8.1,40,1100,https://movie.douban.com/subject/1783457/,https://img9.doubanio.com/view/photo/s_ratio_p...,1783457,功夫熊猫 Kung Fu Panda,\n 首度以人见人...
19,[乔什·库雷],玩具总动员4,"[汤姆·汉克斯, 蒂姆·艾伦, 安妮·波茨, 托尼·海尔, 科甘-迈克尔·凯]",8.6,45,1968,https://movie.douban.com/subject/6850547/,https://img9.doubanio.com/view/photo/s_ratio_p...,6850547,玩具总动员4 Toy Story 4,\n 胡迪深知自己在这个世...

In [16]:
directors=[]
rate=[]
star=[]
urls=[]
title=[]
cover=[]
id=[]
for i in range(5):
    url='https://movie.douban.com/j/new_search_subjects?sort=U&range=0,10&tags=&start='+str(i*20)+'&genres=%E5%8A%A8%E7%94%BB'
    headers={'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36','Cookie': 'douban-fav-remind=1; ll="118376"; bid=<YOUR_BID>; __guid=223695111.729240448148860800.1583402151364.4736; __yadk_uid=0IggMaTwg9OR3NeNv0SEQMz1RnPa03Sx; _vwo_uuid_v2=D75DD0C035E418C226B48ACC450B10761|337ad7d871e30f5ea494c69700a9f3f8; __gads=ID=3f2d285117c64f3e:T=1584165716:S=ALNI_MZPUcTlgFw-mYF6hS0n7UJJ19W83g; __utmz=30149280.1587183210.6.2.utmcsr=so.com|utmccn=(referral)|utmcmd=referral|utmcct=/link; dbcl2="215514625:7tRmkdPSZfo"; push_noty_num=0; push_doumail_num=0; __utmv=30149280.21551; __utmz=223695111.1587356710.3.2.utmcsr=so.com|utmccn=(referral)|utmcmd=referral|utmcct=/link; ck=brOY; ap_v=0,6.0; __utmc=30149280; __utmc=223695111; _pk_ref.100001.4cf6=%5B%22%22%2C%22%22%2C1588931985%2C%22https%3A%2F%2Fwww.so.com%2Flink%3Fm%3DapKyS4t6lROLn4zfjJTCMdI%252F5mMfMVcUZehS7OEvIUH%252BQaaeXKmfR%252FlLLNsD1aVuAa4V0kQKALYqAtBNG97aTEfhAnBknf%252F10Pk3O6sPLUzmYh13FpGT41dNMhyQoCHn7or463DrHatSV6Y8KHG9Kpg%253D%253D%22%5D; _pk_ses.100001.4cf6=*; __utma=30149280.1916057071.1538976751.1588926892.1588931985.18; __utmb=30149280.0.10.1588931985; __utma=223695111.1789100032.1583402152.1588926892.1588931985.12; __utmt=1; monitor_count=24; _pk_id.100001.4cf6=3044cdacc3a12946.1583402152.12.1588933660.1588930081.; __utmb=223695111.6.10.1588931985'}
    b='bid=<YOUR_BID>; _vwo_uuid_v2=D59AC51BC0C8DC3659831FEF855201CE9|139d0cb11657fa3ec35701d9b39cb08c; gr_user_id=a3ee981a-7cbd-4f79-abcc-a1bb9c439290; __gads=ID=e29d3a6975f5705b:T=1578526650:S=ALNI_MakJixAUM_fECO5RxxO1OXwECDU9A; ll="118371"; trc_cookie_storage=taboola%2520global%253Auser-id%3D316670c5-974f-4a1d-bca1-b1468f11dac3-tuct4f517ca; __yadk_uid=4qUCa157BbRiORs96PyQmeeXS1lDqYhk; douban-profile-remind=1; __utmz=223695111.1579659800.2.2.utmcsr=baidu|utmccn=(organic)|utmcmd=organic|utmctr=%E8%B1%86%E7%93%A3; douban-fav-remind=1; viewed="3040149_2995812_30199061_4011670_33439842_30253066_26997029"; _ga=GA1.2.1427742213.1578526647; push_noty_num=0; push_doumail_num=0; cto_bundle=kMPNCl9Wbm04bE9yNk1IbFl3MkhLSSUyQlZQSElYc0pWTXMlMkZYTHIlMkIlMkJQaFRBUUNveEVXMkIwTktIMUV1OG1TSU5xczVRSDRHS3JuZ1laOVlwc3ZYTzk3VlR4WVdMeGpNS1hsQ01ORFdzQXBQamYxa0R4cUZIaGhiYUpFR1FVY2s0Q2ROMTRvM1dwMGJhOEFiT0ZadnRuMHZ4MyUyRkpRJTNEJTNE; __utmz=30149280.1589079646.29.19.utmcsr=google|utmccn=(organic)|utmcmd=organic|utmctr=(not%20provided); _pk_ref.100001.4cf6=%5B%22%22%2C%22%22%2C1589097016%2C%22https%3A%2F%2Fwww.baidu.com%2Fs%3Fie%3DUTF-8%26wd%3D%25E8%25B1%2586%25E7%2593%25A3%22%5D; _pk_ses.100001.4cf6=*; __utma=30149280.1427742213.1578526647.1589079646.1589097017.30; __utmc=30149280; __utma=223695111.1692093362.1578813832.1588940662.1589097017.5; __utmb=223695111.0.10.1589097017; __utmc=223695111; ap_v=0,6.0; dbcl2="216584294:NBHisAJp02A"; ck=jzQy; __utmt=1; __utmv=30149280.21658; __utmb=30149280.6.10.1589097017; _pk_id.100001.4cf6=0622253e80c3deb2.1578813831.5.1589097344.1588943550.'
    line=b.split(';')
    cookie={}
    for i in line:
        key,value = i.split('=',1)
        cookie[key] = value
    response=requests.get(url,headers=headers,cookies = cookie)
    response.encoding = 'utf-8'
    html = response.json()['data']
    for one in html:
        directors.append(one['directors'])
        rate.append(one['rate'])
        star.append(one['star'])
        cover.append(one['cover'])
        title.append(one['title'])
        id.append(one['id'])
        casts.append(one['casts'])
        cover_x.append(one['cover_x'])
        urls.append(one['url'])

In [17]:
data={'导演':directors,'剧名':title,'演员':casts,'评分':rate,'星星':star,'链接':url,'评价':cover_x,'图片':cover,'id':id}

In [18]:
data

{'导演': [['宫崎骏'],
  ['拜伦·霍华德', '瑞奇·摩尔', '杰拉德·布什'],
  ['饺子'],
  ['新海诚'],
  ['李·昂克里奇', '阿德里安·莫利纳'],
  ['宫崎骏'],
  ['新海诚'],
  ['彼特·道格特', '鲍勃·彼德森'],
  ['安德鲁·斯坦顿'],
  ['宫崎骏'],
  ['皮埃尔·柯芬', '克里斯·雷纳德'],
  ['唐·霍尔', '克里斯·威廉姆斯'],
  ['宫崎骏'],
  ['黄家康', '赵霁'],
  ['罗杰·阿勒斯', '罗伯·明可夫'],
  ['梁旋', '张春'],
  ['柯克·德·米科', '克里斯·桑德斯'],
  ['迪恩·德布洛斯', '克里斯·桑德斯'],
  ['克里斯·巴克', '珍妮弗·李'],
  ['田晓鹏'],
  ['宫崎骏'],
  ['大森贵弘'],
  ['宫崎骏'],
  ['彼特·道格特', '大卫·斯沃曼', '李·昂克里奇'],
  ['宫崎骏'],
  ['卡洛斯·沙尔丹哈', '克里斯·韦奇'],
  ['木头', '皇贞季', '顾杰'],
  ['万籁鸣', '唐澄'],
  ['克里斯·巴克', '珍妮弗·李'],
  ['彼特·道格特', '罗纳尔多·德尔·卡门'],
  ['宫崎骏'],
  ['李·昂克里奇'],
  ['乔恩·费儒'],
  ['米林宏昌'],
  ['鲍勃·佩尔西凯蒂', '彼得·拉姆齐', '罗德尼·罗斯曼'],
  ['瑞奇·摩尔'],
  ['宫崎骏'],
  ['皮埃尔·柯芬', '克里斯·雷纳德'],
  ['马克·奥斯本', '约翰·斯蒂文森'],
  ['乔什·库雷'],
  ['近藤喜文'],
  ['雅各布·海尔', '艾丽卡·海斯'],
  ['马克·奥斯本'],
  ['吕寅荣', '亚历山德罗·卡罗尼'],
  ['吕寅荣'],
  ['新海诚'],
  ['约翰·拉塞特'],
  ['凯尔·巴尔达', '皮埃尔·柯芬', '埃里克·吉隆'],
  ['王树忱', '钱运达', '苏秀', '张欣', '刘风'],
  ['贾斯汀·罗兰'],
  ['安东尼·琼'],
  ['约翰·拉塞特', '艾什·布兰农', '李·昂克里奇'],
  ['不思凡'],
  ['今敏'],
  ['菲尔·约翰斯顿', '瑞奇·摩尔'],
  ['保罗·金'],
  ['罗伯·莱特曼'],
  ['大森贵弘', '伊藤秀树'],
  ['迪恩·德布洛斯'],
  ['新海诚'],
  ['维克多·马尔多纳多',
   '加布里埃尔·彭纳基奥利',
   '阿尔弗雷多·托雷斯',
   '弗兰克·巴尔森',
   '阿尔贝托·米尔戈',
   '蒂姆·米勒',
   '达米安·纽诺',
   '杰罗姆·陈',
   '维塔利·舒舒科',
   '欧文·沙利文',
   '罗伯特·瓦利',
   '戴夫·威尔逊',
   '乔恩·叶',
   '哈维尔·雷西奥·格雷西亚'],
  ['迪恩·德布洛斯'],
  ['严定宪', '王树忱', '徐景达'],
  ['宫崎骏'],
  ['亚当·艾略特'],
  ['凯尔·巴尔达', '皮埃尔·柯芬'],
  ['高畑勋'],
  ['布拉德·伯德'],
  ['克里斯·雷纳德', '亚罗·切尼'],
  ['外崎春雄', '细川秀树', '间岛崇宽', '伊藤祐毅', '野中卓也 ', '五味伸介', '宫原秀二', '高桥贤'],
  ['加斯·詹宁斯', '克里斯托夫·卢尔德莱'],
  ['儿玉兼嗣'],
  ['李豪凌', '王昕'],
  ['细田守'],
  ['贾斯汀·罗兰', '胡安·何塞·梅扎-莱昂'],
  ['黄成希', '危天行'],
  ['安德鲁·斯坦顿', '李·昂克里奇'],
  ['格恩迪·塔塔科夫斯基'],
  ['丹·斯坎隆'],
  ['布拉德·伯德', '简·皮克瓦'],
  ['藤森雅也'],
  ['今敏'],
  ['王昕', '陈烨'],
  ['保罗·金'],
  ['内森·格雷诺', '拜伦·霍华德'],
  ['牛岛新一郎'],
  ['加里·特洛斯达勒', '柯克·维斯'],
  ['罗恩·克莱蒙兹', '约翰·马斯克', '唐·霍尔', '克里斯·威廉姆斯'],
  ['常光希'],
  ['麦克·特米尔', '史蒂夫·马蒂诺'],
  ['约瑟夫·巴伯拉', '威廉·汉纳', '特克斯·艾弗里', 'Michael Lah'],
  ['格恩迪·塔塔科夫斯基'],
  ['卡洛斯·沙尔丹哈'],
  ['刘阔'],
  ['山田尚子'],
  ['克里斯·雷纳德'],
  ['卡洛斯·沙尔丹哈', '麦克·特米尔'],
  ['蒂姆·波顿', '迈克·约翰逊'],
  ['八木龙一', '山崎贵'],
  ['永冈智佳']],
 '剧名': ['千与千寻',
  '疯狂动物城',
  '哪吒之魔童降世',
  '你的名字。',
  '寻梦环游记',
  '龙猫',
  '天气之子',
  '飞屋环游记',
  '机器人总动员',
  '哈尔的移动城堡',
  '神偷奶爸',
  '超能陆战队',
  '天空之城',
  '白蛇：缘起',
  '狮子王',
  '大鱼海棠',
  '疯狂原始人',
  '驯龙高手',
  '冰雪奇缘',
  '西游记之大圣归来',
  '魔女宅急便',
  '萤火之森',
  '幽灵公主',
  '怪兽电力公司',
  '悬崖上的金鱼姬',
  '冰川时代',
  '罗小黑战记',
  '大闹天宫',
  '冰雪奇缘2',
  '头脑特工队',
  '起风了',
  '玩具总动员3',
  '狮子王',
  '借东西的小人阿莉埃蒂',
  '蜘蛛侠：平行宇宙',
  '无敌破坏王',
  '风之谷',
  '神偷奶爸2',
  '功夫熊猫',
  '玩具总动员4',
  '侧耳倾听',
  '瑞克和莫蒂 第四季',
  '小王子',
  '功夫熊猫3',
  '功夫熊猫2',
  '秒速5厘米',
  '玩具总动员',
  '神偷奶爸3',
  '天书奇谭',
  '瑞克和莫蒂 第一季',
  '外星也难民 第一季',
  '玩具总动员2',
  '大护法',
  '红辣椒',
  '无敌破坏王2：大闹互联网',
  '帕丁顿熊2',
  '大侦探皮卡丘',
  '夏目友人帐',
  '驯龙高手2',
  '言叶之庭',
  '爱，死亡和机器人 第一季',
  '驯龙高手3',
  '哪吒闹海',
  '红猪',
  '玛丽和马克思',
  '小黄人大眼萌',
  '萤火虫之墓',
  '超人总动员2',
  '爱宠大机密',
  '鬼灭之刃',
  '欢乐好声音',
  '名侦探柯南：贝克街的亡灵',
  '一人之下 第一季',
  '穿越时空的少女',
  '瑞克和莫蒂 第三季',
  '一人之下 第三季',
  '海底总动员',
  '精灵旅社',
  '怪兽大学',
  '美食总动员',
  '你看起来好像很好吃',
  '未麻的部屋',
  '一人之下 第二季',
  '帕丁顿熊',
  '魔发奇缘',
  '我想吃掉你的胰脏',
  '美女与野兽',
  '海洋奇缘',
  '宝莲灯',
  '冰川时代4',
  '猫和老鼠',
  '精灵旅社2',
  '冰川时代2：融冰之灾',
  '风语咒',
  '声之形',
  '爱宠大机密2',
  '冰川时代3',
  '僵尸新娘',
  '哆啦A梦：伴我同行',
  '名侦探柯南：绀青之拳'],
 '演员': [['高山南', '佐久间玲', '户田惠子', '山口胜平', '信泽三惠子'],
  ['佐仓绫音', '内山昂辉', '辻亲八', '山本兼平', '后藤弘树'],
  ['松田洋治', '石田百合子', '田中裕子', '小林薰', '西村雅彦'],
  ['约翰·古德曼', '比利·克里斯托', '玛丽·吉布斯', '史蒂夫·布西密', '詹姆斯·柯本'],
  ['奈良柚莉爱', '土井洋辉', '山口智子', '长岛一茂', '天海祐希'],
  ['雷·罗马诺', '约翰·雷吉扎莫', '丹尼斯·利瑞', '杰克·布莱克', '克里斯·韦奇'],
  ['山新', '郝祥海', '刘明月'],
  ['邱岳峰', '富润生', '毕克', '尚华', '于鼎'],
  ['克里斯汀·贝尔', '伊迪娜·门泽尔', '乔什·加德', '乔纳森·格罗夫', '杰森·雷特'],
  ['艾米·波勒', '菲利丝·史密斯', '理查德·坎德', '比尔·哈德尔', '刘易斯·布莱克'],
  ['庵野秀明', '泷本美织', '西岛秀俊', '西村雅彦', '史蒂夫·阿尔珀特'],
  ['汤姆·汉克斯', '蒂姆·艾伦', '琼·库萨克', '尼德·巴蒂', '唐·里克斯'],
  ['唐纳德·格洛弗', '阿尔法·伍达德', '詹姆斯·厄尔·琼斯', '切瓦特·埃加福', '科甘-迈克尔·凯'],
  ['志田未来', '神木隆之介', '树木希林', '三浦友和', '大竹忍'],
  ['沙梅克·摩尔', '杰克·约翰逊', '海莉·斯坦菲尔德', '马赫沙拉·阿里', '布莱恩·泰里·亨利'],
  ['约翰·C·赖利', '萨拉·西尔弗曼', '杰克·麦克布瑞尔', '简·林奇', '艾伦·图代克'],
  ['岛本须美', '松田洋治', '榊原良子', '辻村真人', '京田尚子'],
  ['史蒂夫·卡瑞尔', '克里斯汀·韦格', '本杰明·布拉特', '米兰达·卡斯格拉夫', '拉塞尔·布兰德'],
  ['杰克·布莱克', '达斯汀·霍夫曼', '安吉丽娜·朱莉', '伊恩·麦柯肖恩', '成龙'],
  ['汤姆·汉克斯', '蒂姆·艾伦', '安妮·波茨', '托尼·海尔', '科甘-迈克尔·凯'],
  ['柊瑠美', '入野自由', '夏木真理', '菅原文太', '中村彰男'],
  ['金妮弗·古德温', '杰森·贝特曼', '伊德里斯·艾尔巴', '珍妮·斯蕾特', '内特·托伦斯'],
  ['吕艳婷', '囧森瑟夫', '瀚墨', '陈浩', '绿绮'],
  ['神木隆之介', '上白石萌音', '长泽雅美', '市原悦子', '成田凌'],
  ['安东尼·冈萨雷斯', '盖尔·加西亚·贝纳尔', '本杰明·布拉特', '阿兰娜·乌巴赫', '芮妮·维克托'],
  ['日高法子', '坂本千夏', '糸井重里', '岛本须美', '北林谷荣'],
  ['醍醐虎汰朗', '森七菜', '小栗旬', '本田翼', '倍赏千惠子'],
  ['爱德华·阿斯纳', '克里斯托弗·普卢默', '乔丹·长井', '鲍勃·彼德森', '德尔罗伊·林多'],
  ['本·贝尔特', '艾丽莎·奈特', '杰夫·格尔林', '佛莱德·威拉特', '西格妮·韦弗'],
  ['倍赏千惠子', '木村拓哉', '美轮明宏', '我修院达也', '神木隆之介'],
  ['史蒂夫·卡瑞尔', '杰森·席格尔', '拉塞尔·布兰德', '朱莉·安德鲁斯', '威尔·阿奈特'],
  ['斯科特·安第斯', '瑞恩·波特', '丹尼尔·海尼', 'T·J·米勒', '杰米·钟'],
  ['田中真弓', '横泽启子', '初井言荣', '寺田农', '常田富士男'],
  ['张喆', '杨天翔', '唐小喜', '刘紫玲', '张遥函'],
  ['乔纳森·泰勒·托马斯', '马修·布罗德里克', '杰瑞米·艾恩斯', '詹姆斯·厄尔·琼斯', '莫伊拉·凯利'],
  ['季冠霖', '苏尚卿', '许魏洲', '金士杰', '杨婷'],
  ['尼古拉斯·凯奇', '艾玛·斯通', '瑞恩·雷诺兹', '凯瑟琳·基纳', '克萝丽丝·利奇曼'],
  ['杰伊·巴鲁切尔', '杰拉德·巴特勒', '克雷格·费格森', '亚美莉卡·费雷拉', '乔纳·希尔'],
  ['克里斯汀·贝尔', '伊迪娜·门泽尔', '乔纳森·格罗夫', '乔什·加德', '圣蒂诺·方塔纳'],
  ['张磊', '林子杰', '吴文伦', '童自荣', '刘九容'],
  ['高山南', '佐久间玲', '户田惠子', '山口胜平', '信泽三惠子'],
  ['佐仓绫音', '内山昂辉', '辻亲八', '山本兼平', '后藤弘树'],
  ['松田洋治', '石田百合子', '田中裕子', '小林薰', '西村雅彦'],
  ['约翰·古德曼', '比利·克里斯托', '玛丽·吉布斯', '史蒂夫·布西密', '詹姆斯·柯本'],
  ['奈良柚莉爱', '土井洋辉', '山口智子', '长岛一茂', '天海祐希'],
  ['雷·罗马诺', '约翰·雷吉扎莫', '丹尼斯·利瑞', '杰克·布莱克', '克里斯·韦奇'],
  ['山新', '郝祥海', '刘明月'],
  ['邱岳峰', '富润生', '毕克', '尚华', '于鼎'],
  ['克里斯汀·贝尔', '伊迪娜·门泽尔', '乔什·加德', '乔纳森·格罗夫', '杰森·雷特'],
  ['艾米·波勒', '菲利丝·史密斯', '理查德·坎德', '比尔·哈德尔', '刘易斯·布莱克'],
  ['庵野秀明', '泷本美织', '西岛秀俊', '西村雅彦', '史蒂夫·阿尔珀特'],
  ['汤姆·汉克斯', '蒂姆·艾伦', '琼·库萨克', '尼德·巴蒂', '唐·里克斯'],
  ['唐纳德·格洛弗', '阿尔法·伍达德', '詹姆斯·厄尔·琼斯', '切瓦特·埃加福', '科甘-迈克尔·凯'],
  ['志田未来', '神木隆之介', '树木希林', '三浦友和', '大竹忍'],
  ['沙梅克·摩尔', '杰克·约翰逊', '海莉·斯坦菲尔德', '马赫沙拉·阿里', '布莱恩·泰里·亨利'],
  ['约翰·C·赖利', '萨拉·西尔弗曼', '杰克·麦克布瑞尔', '简·林奇', '艾伦·图代克'],
  ['岛本须美', '松田洋治', '榊原良子', '辻村真人', '京田尚子'],
  ['史蒂夫·卡瑞尔', '克里斯汀·韦格', '本杰明·布拉特', '米兰达·卡斯格拉夫', '拉塞尔·布兰德'],
  ['杰克·布莱克', '达斯汀·霍夫曼', '安吉丽娜·朱莉', '伊恩·麦柯肖恩', '成龙'],
  ['汤姆·汉克斯', '蒂姆·艾伦', '安妮·波茨', '托尼·海尔', '科甘-迈克尔·凯'],
  ['本名阳子', '小林桂树', '高山南', '高桥一生', '山下容莉枝'],
  ['贾斯汀·罗兰', '克里斯·帕内尔', '斯宾瑟·格拉默', '萨拉·乔克', '凯瑞·华格伦'],
  ['杰夫·布里吉斯', '麦肯吉·弗依', '瑞秋·麦克亚当斯', '瑞利·奥斯本', '詹姆斯·弗兰科'],
  ['杰克·布莱克', '布莱恩·科兰斯顿', '达斯汀·霍夫曼', '安吉丽娜·朱莉', 'J·K·西蒙斯'],
  ['杰克·布莱克', '安吉丽娜·朱莉', '达斯汀·霍夫曼', '加里·奥德曼', '成龙'],
  ['水桥研二', '近藤好美 ', '花村怜美', '尾上绫华', '水野理纱'],
  ['汤姆·汉克斯', '蒂姆·艾伦', '唐·里克斯', '吉姆·法尼', '唐泽寿明'],
  ['史蒂夫·卡瑞尔', '克里斯汀·韦格', '崔·帕克', '米兰达·卡斯格拉夫', '达纳·盖尔'],
  ['丁建华', '毕克', '苏秀', '程晓桦', '施融'],
  ['贾斯汀·罗兰', '克里斯·帕内尔', '斯宾瑟·格拉默', '萨拉·乔克', '凯瑞·华格伦'],
  ['贾斯汀·罗兰', '托马斯·米德蒂奇', '肖恩·吉布朗尼', '玛丽·麦克', '安德鲁·达利'],
  ['汤姆·汉克斯', '蒂姆·艾伦', '琼·库萨克', '凯尔希·格兰莫', '唐·里克斯'],
  ['小连杀', '图特哈蒙', '金士杰', '幽舞越山', '李佳怡'],
  ['林原惠美', '江守彻', '堀胜之祐', '古谷彻', '大塚明夫'],
  ['约翰·C·赖利', '萨拉·西尔弗曼', '盖尔·加朵', '塔拉吉·P·汉森', '杰克·麦克布瑞尔'],
  ['本·卫肖', '休·格兰特', '休·博纳维尔', '莎莉·霍金斯', '萨缪尔·乔斯林'],
  ['瑞恩·雷诺兹', '贾斯蒂斯·史密斯', '凯瑟琳·纽顿', '克里斯·吉尔', '比尔·奈伊'],
  ['神谷浩史', '井上和彦', '高良健吾', '小林沙苗', '藤村步'],
  ['杰伊·巴鲁切尔', '凯特·布兰切特', '杰拉德·巴特勒', '克雷格·费格森', '亚美莉卡·费雷拉'],
  ['入野自由', '花泽香菜', '平野文', '前田刚', '寺崎裕香'],
  ['斯科特·怀特', '诺兰·诺斯', '马修·杨·金', '迈克尔·本耶尔', '乔什·布雷纳'],
  ['杰伊·巴鲁切尔', '亚美莉卡·费雷拉', 'F·默里·亚伯拉罕', '凯特·布兰切特', '杰拉德·巴特勒'],
  ['梁正晖', '邱岳峰', '毕克', '富润生', '尚华'],
  ['森山周一郎', '加藤登纪子', '冈村明美', '桂三枝', '上条恒彦'],
  ['托妮·科莱特', '菲利普·塞默·霍夫曼', '巴瑞·哈姆弗莱斯', '艾瑞克·巴纳', '贝塔尼·维特莫尔'],
  ['桑德拉·布洛克', '乔恩·哈姆', '迈克尔·基顿', '艾莉森·珍妮', '史蒂夫·库根'],
  ['辰己努', '白石绫乃', '志乃原良子', '山口朱美', '端田宏三'],
  ['格雷格·T·尼尔森', '霍利·亨特', '莎拉·沃威尔', '赫克·米尔纳', '伊莱·富西尔'],
  ['路易·C·K', '艾瑞克·斯通斯崔特', '凯文·哈特', '艾丽·坎伯尔', '史蒂夫·库根'],
  ['花江夏树', '鬼头明里', '下野纮', '松冈祯丞', '冈本信彦'],
  ['马修·麦康纳', '瑞茜·威瑟斯彭', '塞思·麦克法兰', '斯嘉丽·约翰逊', '约翰·C·赖利'],
  ['高山南', '山崎和佳奈', '神谷明', '山口胜平', '林原惠美'],
  ['田丸笃志', '饭田友子', '早见沙织', '野岛健儿', '立花慎之介'],
  ['仲里依纱', '石田卓也', '板仓光隆', '垣内彩未', '谷村美月'],
  ['贾斯汀·罗兰', '克里斯·帕内尔', '斯宾瑟·格拉默', '萨拉·乔克', '内森·菲利安'],
  ['曹云图', '小连杀', '彭尧', '宝木中阳', '阿杰'],
  ['艾伯特·布鲁克斯', '艾伦·德杰尼勒斯', '亚历山大·古尔德', '威廉·达福', '布拉德·加内特'],
  ['亚当·桑德勒', '安迪·萨姆伯格', '赛琳娜·戈麦斯', '凯文·詹姆斯', '法兰·德瑞雪'],
  ['比利·克里斯托', '约翰·古德曼', '史蒂夫·布西密', '海伦·米伦', '彼得·孙'],
  ['帕顿·奥斯瓦尔特', '伊安·霍姆', '卢·罗曼诺', '布莱恩·丹内利', '彼得·孙'],
  ['山口胜平', '爱河里花子', '加藤清史郎', '原田知世', '川岛得爱'],
  ['岩男润子', '松本梨香', '辻亲八', '大仓正章', '秋元羊介'],
  ['曹云图', '小连杀', '彭尧', '宝木中阳', '阿杰'],
  ['本·卫肖', '妮可·基德曼', '休·博纳维尔', '莎莉·霍金斯', '萨缪尔·乔斯林'],
  ['曼迪·摩尔', '扎克瑞·莱维', '唐纳·墨菲', '朗·普尔曼', '迈克·康纳·盖尼'],
  ['高杉真宙', 'Lynn', '藤井雪代', '内田雄马', '福岛润'],
  ['佩吉·奥哈拉', '罗比·本森', '理查德·怀特', '杰里·奥尔巴赫', '戴维·奥格登·施蒂尔斯'],
  ['奥丽伊·卡瓦洛', '道恩·强森', '瑞切尔·豪斯', '特穆拉·莫里森', '杰梅奈·克莱门特'],
  ['姜文', '徐帆', '宁静', '陈佩斯', '崔杰'],
  ['阿兹·安萨里', '乔·贝哈', '克里斯托弗·坎贝尔', '阿兰·夏巴', '伊丝特尔·迪恩'],
  ['道斯·巴特勒', '里德·科菲', '约瑟夫·巴伯拉', '威廉·汉纳', '特克斯·艾弗里'],
  ['亚当·桑德勒', '安迪·萨姆伯格', '赛琳娜·戈麦斯', '阿什·布林克夫', '凯文·詹姆斯'],
  ['雷·罗马诺', '约翰·雷吉扎莫', '丹尼斯·利瑞', '西恩·威廉·斯科特', '乔希·佩克'],
  ['路知行', '阎萌萌', '褚珺', '边江', '山新'],
  ['入野自由', '早见沙织', '悠木碧', '小野贤章', '金子有希'],
  ['帕顿·奥斯瓦尔特', '凯文·哈特', '哈里森·福特', '艾瑞克·斯通斯崔特', '珍妮·斯蕾特'],
  ['雷·罗马诺', '约翰·雷吉扎莫', '丹尼斯·利瑞', '西蒙·佩吉', 'Eunice Cho'],
  ['约翰尼·德普', '海伦娜·伯翰·卡特', '艾米丽·沃森', '崔茜·尤玛', '保罗·怀特豪斯'],
  ['水田山葵', '大原惠美', '嘉数由美', '木村昴', '关智一'],
  ['高山南', '山口胜平', '山崎和佳奈', '小山力也', '绪方贤一']],
 '评分': ['9.4',
  '9.2',
  '8.5',
  '8.4',
  '9.1',
  '9.2',
  '7.1',
  '9.0',
  '9.3',
  '9.1',
  '8.6',
  '8.7',
  '9.1',
  '7.9',
  '9.0',
  '6.8',
  '8.7',
  '8.7',
  '8.4',
  '8.3',
  '8.6',
  '8.9',
  '8.9',
  '8.7',
  '8.5',
  '8.6',
  '8.2',
  '9.3',
  '7.2',
  '8.7',
  '8.1',
  '8.8',
  '7.4',
  '8.8',
  '8.6',
  '8.7',
  '8.9',
  '8.0',
  '8.1',
  '8.6',
  '8.9',
  '9.8',
  '8.2',
  '7.7',
  '8.0',
  '8.3',
  '8.4',
  '6.8',
  '9.2',
  '9.7',
  '9.1',
  '8.3',
  '7.8',
  '9.0',
  '8.1',
  '8.1',
  '6.5',
  '8.1',
  '8.0',
  '8.3',
  '9.2',
  '7.5',
  '9.1',
  '8.5',
  '8.9',
  '7.6',
  '8.7',
  '7.9',
  '7.7',
  '9.1',
  '8.1',
  '9.0',
  '8.8',
  '8.6',
  '9.8',
  '8.0',
  '8.4',
  '7.9',
  '8.2',
  '8.4',
  '8.9',
  '8.9',
  '9.1',
  '7.7',
  '8.2',
  '6.9',
  '8.5',
  '7.6',
  '8.2',
  '8.1',
  '9.7',
  '7.7',
  '8.1',
  '6.9',
  '6.8',
  '7.0',
  '8.3',
  '8.2',
  '8.0',
  '5.9'],
 '星星': ['45',
  '45',
  '45',
  '40',
  '45',
  '45',
  '35',
  '45',
  '45',
  '45',
  '45',
  '45',
  '45',
  '40',
  '45',
  '35',
  '45',
  '45',
  '40',
  '40',
  '45',
  '45',
  '45',
  '45',
  '45',
  '45',
  '40',
  '45',
  '35',
  '45',
  '40',
  '45',
  '35',
  '45',
  '45',
  '45',
  '45',
  '40',
  '40',
  '45',
  '45',
  '50',
  '40',
  '40',
  '40',
  '40',
  '40',
  '35',
  '45',
  '50',
  '45',
  '40',
  '40',
  '45',
  '40',
  '40',
  '35',
  '40',
  '40',
  '40',
  '45',
  '40',
  '45',
  '45',
  '45',
  '40',
  '45',
  '40',
  '40',
  '45',
  '40',
  '45',
  '45',
  '45',
  '50',
  '40',
  '40',
  '40',
  '40',
  '40',
  '45',
  '45',
  '45',
  '40',
  '40',
  '35',
  '45',
  '40',
  '40',
  '40',
  '50',
  '40',
  '40',
  '35',
  '35',
  '35',
  '40',
  '40',
  '40',
  '30'],
 '链接': 'https://movie.douban.com/j/new_search_subjects?sort=U&range=0,10&tags=&start=80&genres=%E5%8A%A8%E7%94%BB',
 '评价': [1067,
  2142,
  2058,
  1277,
  1065,
  672,
  2000,
  800,
  1080,
  1986,
  1024,
  1013,
  2500,
  2142,
  2200,
  770,
  1788,
  5001,
  1100,
  1968,
  1080,
  1418,
  5594,
  1428,
  1432,
  1600,
  5906,
  2700,
  3000,
  1509,
  1013,
  8268,
  2064,
  5315,
  2140,
  1080,
  510,
  1290,
  1373,
  5906,
  1067,
  2142,
  2058,
  1277,
  1065,
  672,
  2000,
  800,
  1080,
  1986,
  1024,
  1013,
  2500,
  2142,
  2200,
  770,
  1788,
  5001,
  1100,
  1968,
  644,
  1200,
  5000,
  2763,
  1466,
  1073,
  1996,
  5512,
  649,
  1280,
  2703,
  2100,
  1080,
  2130,
  1968,
  1800,
  1350,
  5906,
  2976,
  1062,
  1500,
  2000,
  400,
  1767,
  1132,
  1000,
  844,
  1900,
  4200,
  1500,
  1000,
  800,
  700,
  2156,
  523,
  1080,
  2015,
  5000,
  1543,
  500,
  2142,
  443,
  770,
  572,
  1148,
  1134,
  1280,
  1418,
  2622,
  4000,
  402,
  1474,
  1400,
  1079,
  788,
  1000,
  1425,
  800,
  6496,
  7785],
 '图片': ['https://img9.doubanio.com/view/photo/s_ratio_poster/public/p2557573348.jpg',
  'https://img9.doubanio.com/view/photo/s_ratio_poster/public/p2315672647.jpg',
  'https://img9.doubanio.com/view/photo/s_ratio_poster/public/p2563780504.jpg',
  'https://img9.doubanio.com/view/photo/s_ratio_poster/public/p2395733377.jpg',
  'https://img9.doubanio.com/view/photo/s_ratio_poster/public/p2503997609.jpg',
  'https://img9.doubanio.com/view/photo/s_ratio_poster/public/p2540924496.jpg',
  'https://img9.doubanio.com/view/photo/s_ratio_poster/public/p2570059839.jpg',
  'https://img9.doubanio.com/view/photo/s_ratio_poster/public/p485887754.jpg',
  'https://img9.doubanio.com/view/photo/s_ratio_poster/public/p1461851991.jpg',
  'https://img9.doubanio.com/view/photo/s_ratio_poster/public/p2174346180.jpg',
  'https://img9.doubanio.com/view/photo/s_ratio_poster/public/p792776858.jpg',
  'https://img9.doubanio.com/view/photo/s_ratio_poster/public/p2224568669.jpg',
  'https://img9.doubanio.com/view/photo/s_ratio_poster/public/p1446261379.jpg',
  'https://img9.doubanio.com/view/photo/s_ratio_poster/public/p2544313786.jpg',
  'https://img9.doubanio.com/view/photo/s_ratio_poster/public/p2277799019.jpg',
  'https://img9.doubanio.com/view/photo/s_ratio_poster/public/p2361744534.jpg',
  'https://img9.doubanio.com/view/photo/s_ratio_poster/public/p1867084027.jpg',
  'https://img9.doubanio.com/view/photo/s_ratio_poster/public/p2210954024.jpg',
  'https://img9.doubanio.com/view/photo/s_ratio_poster/public/p2166640945.jpg',
  'https://img9.doubanio.com/view/photo/s_ratio_poster/public/p2255028780.jpg',
  'https://img9.doubanio.com/view/photo/s_ratio_poster/public/p456676352.jpg',
  'https://img9.doubanio.com/view/photo/s_ratio_poster/public/p1675053073.jpg',
  'https://img9.doubanio.com/view/photo/s_ratio_poster/public/p1613191025.jpg',
  'https://img9.doubanio.com/view/photo/s_ratio_poster/public/p2513247938.jpg',
  'https://img9.doubanio.com/view/photo/s_ratio_poster/public/p454118602.jpg',
  'https://img9.doubanio.com/view/photo/s_ratio_poster/public/p1910895719.jpg',
  'https://img9.doubanio.com/view/photo/s_ratio_poster/public/p2568288336.jpg',
  'https://img9.doubanio.com/view/photo/s_ratio_poster/public/p2184505167.jpg',
  'https://img9.doubanio.com/view/photo/s_ratio_poster/public/p2572847101.jpg',
  'https://img9.doubanio.com/view/photo/s_ratio_poster/public/p2266293606.jpg',
  'https://img9.doubanio.com/view/photo/s_ratio_poster/public/p1998028598.jpg',
  'https://img9.doubanio.com/view/photo/s_ratio_poster/public/p1283675359.jpg',
  'https://img9.doubanio.com/view/photo/s_ratio_poster/public/p2559742751.jpg',
  'https://img9.doubanio.com/view/photo/s_ratio_poster/public/p617533616.jpg',
  'https://img9.doubanio.com/view/photo/s_ratio_poster/public/p2542867516.jpg',
  'https://img9.doubanio.com/view/photo/s_ratio_poster/public/p1735642656.jpg',
  'https://img9.doubanio.com/view/photo/s_ratio_poster/public/p1917567652.jpg',
  'https://img9.doubanio.com/view/photo/s_ratio_poster/public/p2164225595.jpg',
  'https://img9.doubanio.com/view/photo/s_ratio_poster/public/p1597238857.jpg',
  'https://img9.doubanio.com/view/photo/s_ratio_poster/public/p2557284230.jpg',
  'https://img9.doubanio.com/view/photo/s_ratio_poster/public/p456692072.jpg',
  'https://img9.doubanio.com/view/photo/s_ratio_poster/public/p2573033857.jpg',
  'https://img9.doubanio.com/view/photo/s_ratio_poster/public/p2274029145.jpg',
  'https://img9.doubanio.com/view/photo/s_ratio_poster/public/p2306653420.jpg',
  'https://img9.doubanio.com/view/photo/s_ratio_poster/public/p877183898.jpg',
  'https://img9.doubanio.com/view/photo/s_ratio_poster/public/p982896012.jpg',
  'https://img9.doubanio.com/view/photo/s_ratio_poster/public/p2565956404.jpg',
  'https://img9.doubanio.com/view/photo/s_ratio_poster/public/p2469070974.jpg',
  'https://img9.doubanio.com/view/photo/s_ratio_poster/public/p2515539487.jpg',
  'https://img9.doubanio.com/view/photo/s_ratio_poster/public/p2396871198.jpg',
  'https://img9.doubanio.com/view/photo/s_ratio_poster/public/p2600469202.jpg',
  'https://img9.doubanio.com/view/photo/s_ratio_poster/public/p1283688673.jpg',
  'https://img9.doubanio.com/view/photo/s_ratio_poster/public/p2490948849.jpg',
  'https://img9.doubanio.com/view/photo/s_ratio_poster/public/p456825720.jpg',
  'https://img9.doubanio.com/view/photo/s_ratio_poster/public/p2537667301.jpg',
  'https://img9.doubanio.com/view/photo/s_ratio_poster/public/p2506466229.jpg',
  'https://img9.doubanio.com/view/photo/s_ratio_poster/public/p2555538168.jpg',
  'https://img9.doubanio.com/view/photo/s_ratio_poster/public/p2546745948.jpg',
  'https://img9.doubanio.com/view/photo/s_ratio_poster/public/p2192713707.jpg',
  'https://img9.doubanio.com/view/photo/s_ratio_poster/public/p1958733032.jpg',
  'https://img9.doubanio.com/view/photo/s_ratio_poster/public/p2548248276.jpg',
  'https://img9.doubanio.com/view/photo/s_ratio_poster/public/p2546335362.jpg',
  'https://img9.doubanio.com/view/photo/s_ratio_poster/public/p2516566783.jpg',
  'https://img9.doubanio.com/view/photo/s_ratio_poster/public/p1637195728.jpg',
  'https://img9.doubanio.com/view/photo/s_ratio_poster/public/p2162822165.jpg',
  'https://img9.doubanio.com/view/photo/s_ratio_poster/public/p2265761240.jpg',
  'https://img9.doubanio.com/view/photo/s_ratio_poster/public/p1157334208.jpg',
  'https://img9.doubanio.com/view/photo/s_ratio_poster/public/p2522880251.jpg',
  'https://img9.doubanio.com/view/photo/s_ratio_poster/public/p2363369616.jpg',
  'https://img9.doubanio.com/view/photo/s_ratio_poster/public/p2551222097.jpg',
  'https://img9.doubanio.com/view/photo/s_ratio_poster/public/p2411622136.jpg',
  'https://img9.doubanio.com/view/photo/s_ratio_poster/public/p453731188.jpg',
  'https://img9.doubanio.com/view/photo/s_ratio_poster/public/p2370126919.jpg',
  'https://img9.doubanio.com/view/photo/s_ratio_poster/public/p2079334286.jpg',
  'https://img9.doubanio.com/view/photo/s_ratio_poster/public/p2492804476.jpg',
  'https://img9.doubanio.com/view/photo/s_ratio_poster/public/p2561547232.jpg',
  'https://img9.doubanio.com/view/photo/s_ratio_poster/public/p1755893801.jpg',
  'https://img9.doubanio.com/view/photo/s_ratio_poster/public/p2155072056.jpg',
  'https://img9.doubanio.com/view/photo/s_ratio_poster/public/p2033476722.jpg',
  'https://img9.doubanio.com/view/photo/s_ratio_poster/public/p465604496.jpg',
  'https://img9.doubanio.com/view/photo/s_ratio_poster/public/p709670262.jpg',
  'https://img9.doubanio.com/view/photo/s_ratio_poster/public/p1351050722.jpg',
  'https://img9.doubanio.com/view/photo/s_ratio_poster/public/p2503247980.jpg',
  'https://img9.doubanio.com/view/photo/s_ratio_poster/public/p2231740424.jpg',
  'https://img9.doubanio.com/view/photo/s_ratio_poster/public/p707509468.jpg',
  'https://img9.doubanio.com/view/photo/s_ratio_poster/public/p2545571306.jpg',
  'https://img9.doubanio.com/view/photo/s_ratio_poster/public/p2238467474.jpg',
  'https://img9.doubanio.com/view/photo/s_ratio_poster/public/p2397960879.jpg',
  'https://img9.doubanio.com/view/photo/s_ratio_poster/public/p2195312435.jpg',
  'https://img9.doubanio.com/view/photo/s_ratio_poster/public/p1634625172.jpg',
  'https://img9.doubanio.com/view/photo/s_ratio_poster/public/p2247237724.jpg',
  'https://img9.doubanio.com/view/photo/s_ratio_poster/public/p2276842218.jpg',
  'https://img9.doubanio.com/view/photo/s_ratio_poster/public/p2204578670.jpg',
  'https://img9.doubanio.com/view/photo/s_ratio_poster/public/p2530872223.jpg',
  'https://img9.doubanio.com/view/photo/s_ratio_poster/public/p2497136132.jpg',
  'https://img9.doubanio.com/view/photo/s_ratio_poster/public/p2555923582.jpg',
  'https://img9.doubanio.com/view/photo/s_ratio_poster/public/p2213132432.jpg',
  'https://img9.doubanio.com/view/photo/s_ratio_poster/public/p735361409.jpg',
  'https://img9.doubanio.com/view/photo/s_ratio_poster/public/p2244958975.jpg',