In [1]:
#爬取网址：https://movie.douban.com/tv

In [1]:
import requests
import pandas as pd
from lxml import etree
import json

In [2]:
proxies = {
        'http': '218.14.115.211:3128',
       # 'https': '218.14.115.211:3128'
    }

In [4]:
#热门url='https://movie.douban.com/tv/#!type=tv&tag=%E7%83%AD%E9%97%A8&sort=recommend&page_limit=20&page_start=0'
#美剧url='https://movie.douban.com/tv/#!type=tv&tag=%E7%BE%8E%E5%89%A7&sort=recommend&page_limit=20&page_start=0'
#英剧url='https://movie.douban.com/tv/#!type=tv&tag=%E8%8B%B1%E5%89%A7&sort=recommend&page_limit=20&page_start=0'
#韩剧url='https://movie.douban.com/tv/#!type=tv&tag=%E9%9F%A9%E5%89%A7&sort=recommend&page_limit=20&page_start=0'
#日剧url='https://movie.douban.com/tv/#!type=tv&tag=%E6%97%A5%E5%89%A7&sort=recommend&page_limit=20&page_start=0'
#国产剧url='https://movie.douban.com/tv/#!type=tv&tag=%E5%9B%BD%E4%BA%A7%E5%89%A7&sort=recommend&page_limit=20&page_start=0'
#港剧url='https://movie.douban.com/tv/#!type=tv&tag=%E6%B8%AF%E5%89%A7&sort=recommend&page_limit=20&page_start=0'
#日本动画url='https://movie.douban.com/tv/#!type=tv&tag=%E6%97%A5%E6%9C%AC%E5%8A%A8%E7%94%BB&sort=recommend&page_limit=20&page_start=0'
#综艺url='https://movie.douban.com/tv/#!type=tv&tag=%E7%BB%BC%E8%89%BA&sort=recommend&page_limit=20&page_start=0'
#纪录片url='https://movie.douban.com/tv/#!type=tv&tag=%E7%BA%AA%E5%BD%95%E7%89%87&sort=recommend&page_limit=20&page_start=0'

从网址分析，tag表示电视剧类型['热门','美剧','英剧','韩剧','日剧','国产剧','港剧','日本动画','综艺','纪录片']

由此分析可以构造url='https://movie.douban.com/tv/#!type=tv&tag='+''

# 一、从爬一个标签开始（热门）

In [2]:
url='https://movie.douban.com/j/search_subjects?type=tv&tag=%E7%83%AD%E9%97%A8&sort=recommend&page_limit=20&page_start=0'
headers={'User-Agent':'Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Mobile Safari/537.36'}
b='bid=<YOUR_BID>; ll="118371"; _pk_ref.100001.4cf6=%5B%22%22%2C%22%22%2C1588852453%2C%22https%3A%2F%2Fwww.baidu.com%2Flink%3Furl%3Dv7O7Lwa4weVH-oX_cDZJXveRz9ZRnNO8Pq2sTaW5NoYlQkfT2fJVU2mWySm1yMSK%26wd%3D%26eqid%3Dbd3df8ee0011778d000000065eb3f6df%22%5D; _pk_ses.100001.4cf6=*; ap_v=0,6.0; __utma=30149280.1791132916.1588852454.1588852454.1588852454.1; __utmb=30149280.0.10.1588852454; __utmc=30149280; __utmz=30149280.1588852454.1.1.utmcsr=baidu|utmccn=(organic)|utmcmd=organic; __utma=223695111.309733471.1588852454.1588852454.1588852454.1; __utmb=223695111.0.10.1588852454; __utmc=223695111; __utmz=223695111.1588852454.1.1.utmcsr=baidu|utmccn=(organic)|utmcmd=organic; __yadk_uid=0xAdnlOIp2514fY76HiBNOcBVRTwNicT; _vwo_uuid_v2=D30351479FEA5D4D7B202B2904B842D1A|3965c4303ef845890acaf7da75adae73; _pk_id.100001.4cf6=add6bfe17922d345.1588852453.1.1588852476.1588852453.'
line=b.split(';')
cookie={}
for i in line:
    key,value = i.split('=',1)
    cookie[key] = value

In [3]:
response=requests.get(url,headers=headers,cookies=cookie)

In [4]:
print(response.status_code)

200

In [5]:
response.encoding = 'utf-8'
html = response.json()  # 将json格式的字符串转为python数据类型
html

{'subjects': [{'rate': '8.9',
   'cover_x': 2000,
   'title': '隐秘的角落',
   'url': 'https://movie.douban.com/subject/33404425/',
   'playable': True,
   'cover': 'https://img9.doubanio.com/view/photo/s_ratio_poster/public/p2609064048.jpg',
   'id': '33404425',
   'cover_y': 2998,
   'is_new': False},
  {'rate': '8.7',
   'cover_x': 2500,
   'title': '虽然是精神病但没关系',
   'url': 'https://movie.douban.com/subject/34861170/',
   'playable': False,
   'cover': 'https://img9.doubanio.com/view/photo/s_ratio_poster/public/p2607088315.jpg',
   'id': '34861170',
   'cover_y': 3542,
   'is_new': False},
  {'rate': '6.0',
   'cover_x': 1500,
   'title': '修女战士',
   'url': 'https://movie.douban.com/subject/34788127/',
   'playable': False,
   'cover': 'https://img9.doubanio.com/view/photo/s_ratio_poster/public/p2609365782.jpg',
   'id': '34788127',
   'cover_y': 2222,
   'is_new': True},
  {'rate': '8.0',
   'cover_x': 634,
   'title': '未解之谜',
   'url': 'https://movie.douban.com/subject/35116463/',
   'playable': False,
   'cover': 'https://img9.doubanio.com/view/photo/s_ratio_poster/public/p2610558638.jpg',
   'id': '35116463',
   'cover_y': 939,
   'is_new': True},
  {'rate': '6.8',
   'cover_x': 1080,
   'title': '咒怨：诅咒之家',
   'url': 'https://movie.douban.com/subject/34443566/',
   'playable': False,
   'cover': 'https://img9.doubanio.com/view/photo/s_ratio_poster/public/p2610382497.jpg',
   'id': '34443566',
   'cover_y': 1563,
   'is_new': True},
  {'rate': '8.3',
   'cover_x': 1080,
   'title': '乘风破浪的姐姐',
   'url': 'https://movie.douban.com/subject/34894589/',
   'playable': False,
   'cover': 'https://img9.doubanio.com/view/photo/s_ratio_poster/public/p2608297477.jpg',
   'id': '34894589',
   'cover_y': 1556,
   'is_new': False},
  {'rate': '8.3',
   'cover_x': 1080,
   'title': '少年游之一寸相思',
   'url': 'https://movie.douban.com/subject/30426829/',
   'playable': True,
   'cover': 'https://img9.doubanio.com/view/photo/s_ratio_poster/public/p2606589900.jpg',
   'id': '30426829',
   'cover_y': 1533,
   'is_new': False},
  {'rate': '8.0',
   'cover_x': 1080,
   'title': '怪你过分美丽',
   'url': 'https://movie.douban.com/subject/30486573/',
   'playable': True,
   'cover': 'https://img9.doubanio.com/view/photo/s_ratio_poster/public/p2607365765.jpg',
   'id': '30486573',
   'cover_y': 1520,
   'is_new': False},
  {'rate': '8.2',
   'cover_x': 877,
   'title': '无证之罪',
   'url': 'https://movie.douban.com/subject/26930540/',
   'playable': True,
   'cover': 'https://img9.doubanio.com/view/photo/s_ratio_poster/public/p2497732763.jpg',
   'id': '26930540',
   'cover_y': 1279,
   'is_new': False},
  {'rate': '5.4',
   'cover_x': 752,
   'title': '局中人',
   'url': 'https://movie.douban.com/subject/30329909/',
   'playable': True,
   'cover': 'https://img9.doubanio.com/view/photo/s_ratio_poster/public/p2555427086.jpg',
   'id': '30329909',
   'cover_y': 1274,
   'is_new': True},
  {'rate': '7.0',
   'cover_x': 3543,
   'title': '暮白首',
   'url': 'https://movie.douban.com/subject/30446742/',
   'playable': True,
   'cover': 'https://img9.doubanio.com/view/photo/s_ratio_poster/public/p2608228601.jpg',
   'id': '30446742',
   'cover_y': 5475,
   'is_new': False},
  {'rate': '3.6',
   'cover_x': 1080,
   'title': '爱我就别想太多',
   'url': 'https://movie.douban.com/subject/27012998/',
   'playable': True,
   'cover': 'https://img9.doubanio.com/view/photo/s_ratio_poster/public/p2500704842.jpg',
   'id': '27012998',
   'cover_y': 1440,
   'is_new': True},
  {'rate': '7.5',
   'cover_x': 4429,
   'title': '传闻中的陈芊芊',
   'url': 'https://movie.douban.com/subject/34463197/',
   'playable': True,
   'cover': 'https://img9.doubanio.com/view/photo/s_ratio_poster/public/p2602398693.jpg',
   'id': '34463197',
   'cover_y': 6791,
   'is_new': False},
  {'rate': '7.3',
   'cover_x': 1500,
   'title': '十日游戏',
   'url': 'https://movie.douban.com/subject/26986843/',
   'playable': True,
   'cover': 'https://img9.doubanio.com/view/photo/s_ratio_poster/public/p2606307565.jpg',
   'id': '26986843',
   'cover_y': 2667,
   'is_new': False},
  {'rate': '7.7',
   'cover_x': 2953,
   'title': '三叉戟',
   'url': 'https://movie.douban.com/subject/34845712/',
   'playable': True,
   'cover': 'https://img9.doubanio.com/view/photo/s_ratio_poster/public/p2607650553.jpg',
   'id': '34845712',
   'cover_y': 4528,
   'is_new': False},
  {'rate': '9.5',
   'cover_x': 3000,
   'title': '暗黑 第三季',
   'url': 'https://movie.douban.com/subject/34442364/',
   'playable': False,
   'cover': 'https://img9.doubanio.com/view/photo/s_ratio_poster/public/p2609692563.jpg',
   'id': '34442364',
   'cover_y': 4444,
   'is_new': True},
  {'rate': '8.2',
   'cover_x': 2000,
   'title': '我才不要和你做朋友呢',
   'url': 'https://movie.douban.com/subject/34863327/',
   'playable': True,
   'cover': 'https://img9.doubanio.com/view/photo/s_ratio_poster/public/p2603121645.jpg',
   'id': '34863327',
   'cover_y': 3201,
   'is_new': False},
  {'rate': '9.0',
   'cover_x': 1200,
   'title': '白夜追凶',
   'url': 'https://movie.douban.com/subject/26883064/',
   'playable': True,
   'cover': 'https://img9.doubanio.com/view/photo/s_ratio_poster/public/p2483150767.jpg',
   'id': '26883064',
   'cover_y': 2134,
   'is_new': False},
  {'rate': '9.4',
   'cover_x': 1200,
   'title': '机智医生生活',
   'url': 'https://movie.douban.com/subject/33464863/',
   'playable': False,
   'cover': 'https://img9.doubanio.com/view/photo/s_ratio_poster/public/p2586800409.jpg',
   'id': '33464863',
   'cover_y': 1700,
   'is_new': False},
  {'rate': '8.8',
   'cover_x': 1458,
   'title': '普通人',
   'url': 'https://movie.douban.com/subject/33477335/',
   'playable': False,
   'cover': 'https://img9.doubanio.com/view/photo/s_ratio_poster/public/p2595064425.jpg',
   'id': '33477335',
   'cover_y': 2048,
   'is_new': False}]}

In [6]:
html1=html['subjects']
print(html1)

[{'rate': '8.9', 'cover_x': 2000, 'title': '隐秘的角落', 'url': 'https://movie.douban.com/subject/33404425/', 'playable': True, 'cover': 'https://img9.doubanio.com/view/photo/s_ratio_poster/public/p2609064048.jpg', 'id': '33404425', 'cover_y': 2998, 'is_new': False}, {'rate': '8.7', 'cover_x': 2500, 'title': '虽然是精神病但没关系', 'url': 'https://movie.douban.com/subject/34861170/', 'playable': False, 'cover': 'https://img9.doubanio.com/view/photo/s_ratio_poster/public/p2607088315.jpg', 'id': '34861170', 'cover_y': 3542, 'is_new': False}, {'rate': '6.0', 'cover_x': 1500, 'title': '修女战士', 'url': 'https://movie.douban.com/subject/34788127/', 'playable': False, 'cover': 'https://img9.doubanio.com/view/photo/s_ratio_poster/public/p2609365782.jpg', 'id': '34788127', 'cover_y': 2222, 'is_new': True}, {'rate': '8.0', 'cover_x': 634, 'title': '未解之谜', 'url': 'https://movie.douban.com/subject/35116463/', 'playable': False, 'cover': 'https://img9.doubanio.com/view/photo/s_ratio_poster/public/p2610558638.jpg', 'id': '35116463', 'cover_y': 939, 'is_new': True}, {'rate': '6.8', 'cover_x': 1080, 'title': '咒怨：诅咒之家', 'url': 'https://movie.douban.com/subject/34443566/', 'playable': False, 'cover': 'https://img9.doubanio.com/view/photo/s_ratio_poster/public/p2610382497.jpg', 'id': '34443566', 'cover_y': 1563, 'is_new': True}, {'rate': '8.3', 'cover_x': 1080, 'title': '乘风破浪的姐姐', 'url': 'https://movie.douban.com/subject/34894589/', 'playable': False, 'cover': 'https://img9.doubanio.com/view/photo/s_ratio_poster/public/p2608297477.jpg', 'id': '34894589', 'cover_y': 1556, 'is_new': False}, {'rate': '8.3', 'cover_x': 1080, 'title': '少年游之一寸相思', 'url': 'https://movie.douban.com/subject/30426829/', 'playable': True, 'cover': 'https://img9.doubanio.com/view/photo/s_ratio_poster/public/p2606589900.jpg', 'id': '30426829', 'cover_y': 1533, 'is_new': False}, {'rate': '8.0', 'cover_x': 1080, 'title': '怪你过分美丽', 'url': 'https://movie.douban.com/subject/30486573/', 'playable': True, 'cover': 'https://img9.doubanio.com/view/photo/s_ratio_poster/public/p2607365765.jpg', 'id': '30486573', 'cover_y': 1520, 'is_new': False}, {'rate': '8.2', 'cover_x': 877, 'title': '无证之罪', 'url': 'https://movie.douban.com/subject/26930540/', 'playable': True, 'cover': 'https://img9.doubanio.com/view/photo/s_ratio_poster/public/p2497732763.jpg', 'id': '26930540', 'cover_y': 1279, 'is_new': False}, {'rate': '5.4', 'cover_x': 752, 'title': '局中人', 'url': 'https://movie.douban.com/subject/30329909/', 'playable': True, 'cover': 'https://img9.doubanio.com/view/photo/s_ratio_poster/public/p2555427086.jpg', 'id': '30329909', 'cover_y': 1274, 'is_new': True}, {'rate': '7.0', 'cover_x': 3543, 'title': '暮白首', 'url': 'https://movie.douban.com/subject/30446742/', 'playable': True, 'cover': 'https://img9.doubanio.com/view/photo/s_ratio_poster/public/p2608228601.jpg', 'id': '30446742', 'cover_y': 5475, 'is_new': False}, {'rate': '3.6', 'cover_x': 1080, 'title': '爱我就别想太多', 'url': 'https://movie.douban.com/subject/27012998/', 'playable': True, 'cover': 'https://img9.doubanio.com/view/photo/s_ratio_poster/public/p2500704842.jpg', 'id': '27012998', 'cover_y': 1440, 'is_new': True}, {'rate': '7.5', 'cover_x': 4429, 'title': '传闻中的陈芊芊', 'url': 'https://movie.douban.com/subject/34463197/', 'playable': True, 'cover': 'https://img9.doubanio.com/view/photo/s_ratio_poster/public/p2602398693.jpg', 'id': '34463197', 'cover_y': 6791, 'is_new': False}, {'rate': '7.3', 'cover_x': 1500, 'title': '十日游戏', 'url': 'https://movie.douban.com/subject/26986843/', 'playable': True, 'cover': 'https://img9.doubanio.com/view/photo/s_ratio_poster/public/p2606307565.jpg', 'id': '26986843', 'cover_y': 2667, 'is_new': False}, {'rate': '7.7', 'cover_x': 2953, 'title': '三叉戟', 'url': 'https://movie.douban.com/subject/34845712/', 'playable': True, 'cover': 'https://img9.doubanio.com/view/photo/s_ratio_poster/public/p2607650553.jpg', 'id': '34845712', 'cover_y': 4528, 'is_new': False}, {'rate': '9.5', 'cover_x': 3000, 'title': '暗黑 第三季', 'url': 'https://movie.douban.com/subject/34442364/', 'playable': False, 'cover': 'https://img9.doubanio.com/view/photo/s_ratio_poster/public/p2609692563.jpg', 'id': '34442364', 'cover_y': 4444, 'is_new': True}, {'rate': '8.2', 'cover_x': 2000, 'title': '我才不要和你做朋友呢', 'url': 'https://movie.douban.com/subject/34863327/', 'playable': True, 'cover': 'https://img9.doubanio.com/view/photo/s_ratio_poster/public/p2603121645.jpg', 'id': '34863327', 'cover_y': 3201, 'is_new': False}, {'rate': '9.0', 'cover_x': 1200, 'title': '白夜追凶', 'url': 'https://movie.douban.com/subject/26883064/', 'playable': True, 'cover': 'https://img9.doubanio.com/view/photo/s_ratio_poster/public/p2483150767.jpg', 'id': '26883064', 'cover_y': 2134, 'is_new': False}, {'rate': '9.4', 'cover_x': 1200, 'title': '机智医生生活', 'url': 'https://movie.douban.com/subject/33464863/', 'playable': False, 'cover': 'https://img9.doubanio.com/view/photo/s_ratio_poster/public/p2586800409.jpg', 'id': '33464863', 'cover_y': 1700, 'is_new': False}, {'rate': '8.8', 'cover_x': 1458, 'title': '普通人', 'url': 'https://movie.douban.com/subject/33477335/', 'playable': False, 'cover': 'https://img9.doubanio.com/view/photo/s_ratio_poster/public/p2595064425.jpg', 'id': '33477335', 'cover_y': 2048, 'is_new': False}]

In [7]:
name=[]
score=[]
pnumber=[]
url=[]
cover=[]
id=[]
for one in html1:
    name.append(one['title'])
    score.append(one['rate'])
    pnumber.append(one['cover_y'])
    url.append(one['url'])
    cover.append(one['cover'])
    id.append(one['id'])
print(url)

['https://movie.douban.com/subject/33404425/', 'https://movie.douban.com/subject/34861170/', 'https://movie.douban.com/subject/34788127/', 'https://movie.douban.com/subject/35116463/', 'https://movie.douban.com/subject/34443566/', 'https://movie.douban.com/subject/34894589/', 'https://movie.douban.com/subject/30426829/', 'https://movie.douban.com/subject/30486573/', 'https://movie.douban.com/subject/26930540/', 'https://movie.douban.com/subject/30329909/', 'https://movie.douban.com/subject/30446742/', 'https://movie.douban.com/subject/27012998/', 'https://movie.douban.com/subject/34463197/', 'https://movie.douban.com/subject/26986843/', 'https://movie.douban.com/subject/34845712/', 'https://movie.douban.com/subject/34442364/', 'https://movie.douban.com/subject/34863327/', 'https://movie.douban.com/subject/26883064/', 'https://movie.douban.com/subject/33464863/', 'https://movie.douban.com/subject/33477335/']

In [8]:
len(url)

20

In [9]:
columns={'剧名':name,'评分':score,'点评数':pnumber,'url':url,'图片':cover,'id':id}

In [10]:
data=pd.DataFrame(columns)
data.shape

(20, 6)

In [11]:
data

,剧名,评分,点评数,url,图片,id
0,隐秘的角落,8.9,2998,https://movie.douban.com/subject/33404425/,https://img9.doubanio.com/view/photo/s_ratio_p...,33404425
1,虽然是精神病但没关系,8.7,3542,https://movie.douban.com/subject/34861170/,https://img9.doubanio.com/view/photo/s_ratio_p...,34861170
2,修女战士,6.0,2222,https://movie.douban.com/subject/34788127/,https://img9.doubanio.com/view/photo/s_ratio_p...,34788127
3,未解之谜,8.0,939,https://movie.douban.com/subject/35116463/,https://img9.doubanio.com/view/photo/s_ratio_p...,35116463
4,咒怨：诅咒之家,6.8,1563,https://movie.douban.com/subject/34443566/,https://img9.doubanio.com/view/photo/s_ratio_p...,34443566
5,乘风破浪的姐姐,8.3,1556,https://movie.douban.com/subject/34894589/,https://img9.doubanio.com/view/photo/s_ratio_p...,34894589
6,少年游之一寸相思,8.3,1533,https://movie.douban.com/subject/30426829/,https://img9.doubanio.com/view/photo/s_ratio_p...,30426829
7,怪你过分美丽,8.0,1520,https://movie.douban.com/subject/30486573/,https://img9.doubanio.com/view/photo/s_ratio_p...,30486573
8,无证之罪,8.2,1279,https://movie.douban.com/subject/26930540/,https://img9.doubanio.com/view/photo/s_ratio_p...,26930540
9,局中人,5.4,1274,https://movie.douban.com/subject/30329909/,https://img9.doubanio.com/view/photo/s_ratio_p...,30329909
10,暮白首,7.0,5475,https://movie.douban.com/subject/30446742/,https://img9.doubanio.com/view/photo/s_ratio_p...,30446742
11,爱我就别想太多,3.6,1440,https://movie.douban.com/subject/27012998/,https://img9.doubanio.com/view/photo/s_ratio_p...,27012998
12,传闻中的陈芊芊,7.5,6791,https://movie.douban.com/subject/34463197/,https://img9.doubanio.com/view/photo/s_ratio_p...,34463197
13,十日游戏,7.3,2667,https://movie.douban.com/subject/26986843/,https://img9.doubanio.com/view/photo/s_ratio_p...,26986843
14,三叉戟,7.7,4528,https://movie.douban.com/subject/34845712/,https://img9.doubanio.com/view/photo/s_ratio_p...,34845712
15,暗黑 第三季,9.5,4444,https://movie.douban.com/subject/34442364/,https://img9.doubanio.com/view/photo/s_ratio_p...,34442364
16,我才不要和你做朋友呢,8.2,3201,https://movie.douban.com/subject/34863327/,https://img9.doubanio.com/view/photo/s_ratio_p...,34863327
17,白夜追凶,9.0,2134,https://movie.douban.com/subject/26883064/,https://img9.doubanio.com/view/photo/s_ratio_p...,26883064
18,机智医生生活,9.4,1700,https://movie.douban.com/subject/33464863/,https://img9.doubanio.com/view/photo/s_ratio_p...,33464863
19,普通人,8.8,2048,https://movie.douban.com/subject/33477335/,https://img9.doubanio.com/view/photo/s_ratio_p...,33477335

In [33]:
title=[]
jianj=[]
juqing=[]
otherlike=[]
biaoqian=[]
watch=[]

for i in range(len(data['url'])):
    res=requests.get(data['url'][i],headers=headers,cookies=cookie)
    html = etree.HTML(res.text)
    title.append(''.join(html.xpath('//div[@class="sub-title"]/text()')))
    jianj.append(''.join(html.xpath('//div[@class="sub-meta"]/text()')))
    juqing.append(''.join(html.xpath('//div[@class="bd"]/p/text()')))
    otherlike.append(''.join(html.xpath('//div[@class="wp"]/h3/text()')))
    biaoqian.append(''.join(html.xpath('//div[@class="con remark"]/a/text()')))
    watch.append(''.join(html.xpath('//span[@class="vendor-text"]/text()')))

In [13]:
columns={'剧名':title,'简介':jianj,'剧情':juqing,'还喜欢':otherlike,'标签':biaoqian,'观看':watch}
df=pd.DataFrame(columns)

In [14]:
df.head()

  剧名 简介 剧情 还喜欢 标签 观看
0
1
2
3
4

## 二、爬取加载更多第一次那一页的数据

In [50]:
url='https://movie.douban.com/j/search_subjects?type=tv&tag=%E7%83%AD%E9%97%A8&sort=recommend&page_limit=20&page_start=20'
headers={'User-Agent':'Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Mobile Safari/537.36'}
b='bid="Q+TyquofF3k"; __gads=ID=27c34c24591f68b8:T=1583826922:S=ALNI_MYTBT08_oTj8FoP0Ub_rIKIeR_gkg; __utmc=30149280; __utmz=30149280.1583826934.1.1.utmcsr=baidu|utmccn=(organic)|utmcmd=organic; _vwo_uuid_v2=D38A74B855BBE6DEEA011650D499503FA|724b25b8fa8f857bd49036a32f21b010; ll="118371"; ap_v=0,6.0; gr_user_id=cde4f6c4-366d-446d-bbdb-7a91208d4dfc; __utma=30149280.426755224.1583826934.1583826934.1583934927.2; _pk_ref.100001.4cf6=%5B%22%22%2C%22%22%2C1583934928%2C%22https%3A%2F%2Fwww.baidu.com%2Fs%3Fie%3DUTF-8%26wd%3D%25E8%25B1%2586%25E7%2593%25A3%22%5D; _pk_ses.100001.4cf6=*; __utma=223695111.937284787.1583934929.1583934929.1583934929.1; __utmb=223695111.0.10.1583934929; __utmc=223695111; __utmz=223695111.1583934929.1.1.utmcsr=baidu|utmccn=(organic)|utmcmd=organic|utmctr=%E8%B1%86%E7%93%A3; __yadk_uid=ZCiNH3mBQOmatFURzBilWB3ZG7CcNAlS; push_noty_num=0; push_doumail_num=0; dbcl2="164789361:tRUWWY3I3X8"; ck=m_O9; __utmt=1; __utmv=30149280.16478; __utmb=30149280.3.10.1583934927; _pk_id.100001.4cf6=0cfb4938b254bf7c.1583934928.1.1583937455.1583934928.'
line=b.split(';')
cookie={}
for i in line:
    key,value = i.split('=',1)
    cookie[key] = value

In [51]:
d = {
    'type': 'tv',
    'tag': '热门',
    'page_limit': 20,
    'page_start': 20
}

In [52]:
response=requests.get(url,headers=headers,cookies=cookie,params=d)
print(response.status_code)

200

In [53]:
response.encoding = 'utf-8'
html = response.json()  # 将json格式的字符串转为python数据类型
html1=html['subjects']
print(html1)

[{'rate': '7.3', 'cover_x': 750, 'title': '向往的生活 第四季', 'url': 'https://movie.douban.com/subject/34861173/', 'playable': False, 'cover': 'https://img9.doubanio.com/view/photo/s_ratio_poster/public/p2595985553.jpg', 'id': '34861173', 'cover_y': 1000, 'is_new': False}, {'rate': '8.0', 'cover_x': 640, 'title': '杀手', 'url': 'https://movie.douban.com/subject/30299248/', 'playable': True, 'cover': 'https://img9.doubanio.com/view/photo/s_ratio_poster/public/p2610245641.jpg', 'id': '30299248', 'cover_y': 960, 'is_new': True}, {'rate': '6.8', 'cover_x': 452, 'title': '99分女朋友', 'url': 'https://movie.douban.com/subject/33475999/', 'playable': False, 'cover': 'https://img9.doubanio.com/view/photo/s_ratio_poster/public/p2610264226.jpg', 'id': '33475999', 'cover_y': 800, 'is_new': False}, {'rate': '8.8', 'cover_x': 637, 'title': '寻味东莞', 'url': 'https://movie.douban.com/subject/35099748/', 'playable': True, 'cover': 'https://img9.doubanio.com/view/photo/s_ratio_poster/public/p2609011638.jpg', 'id': '35099748', 'cover_y': 950, 'is_new': False}, {'rate': '8.3', 'cover_x': 1446, 'title': 'Life 线上的我们', 'url': 'https://movie.douban.com/subject/35000628/', 'playable': False, 'cover': 'https://img9.doubanio.com/view/photo/s_ratio_poster/public/p2600787835.jpg', 'id': '35000628', 'cover_y': 2048, 'is_new': False}, {'rate': '9.7', 'cover_x': 1701, 'title': '请回答1988', 'url': 'https://movie.douban.com/subject/26302614/', 'playable': True, 'cover': 'https://img9.doubanio.com/view/photo/s_ratio_poster/public/p2272563445.jpg', 'id': '26302614', 'cover_y': 2410, 'is_new': False}, {'rate': '6.8', 'cover_x': 536, 'title': '青春环游记 第二季', 'url': 'https://movie.douban.com/subject/34880852/', 'playable': True, 'cover': 'https://img9.doubanio.com/view/photo/s_ratio_poster/public/p2607628222.jpg', 'id': '34880852', 'cover_y': 928, 'is_new': True}, {'rate': '7.4', 'cover_x': 945, 'title': '便利店新星', 'url': 'https://movie.douban.com/subject/34951001/', 'playable': False, 'cover': 'https://img9.doubanio.com/view/photo/s_ratio_poster/public/p2606985287.jpg', 'id': '34951001', 'cover_y': 1350, 'is_new': False}, {'rate': '9.5', 'cover_x': 709, 'title': '黄石 第三季', 'url': 'https://movie.douban.com/subject/34814172/', 'playable': False, 'cover': 'https://img9.doubanio.com/view/photo/s_ratio_poster/public/p2610247050.jpg', 'id': '34814172', 'cover_y': 961, 'is_new': False}, {'rate': '9.2', 'cover_x': 2953, 'title': '想见你', 'url': 'https://movie.douban.com/subject/30468961/', 'playable': True, 'cover': 'https://img9.doubanio.com/view/photo/s_ratio_poster/public/p2576977981.jpg', 'id': '30468961', 'cover_y': 4134, 'is_new': False}, {'rate': '9.1', 'cover_x': 632, 'title': '新喋喋人生', 'url': 'https://movie.douban.com/subject/35049287/', 'playable': False, 'cover': 'https://img9.doubanio.com/view/photo/s_ratio_poster/public/p2610784934.jpg', 'id': '35049287', 'cover_y': 818, 'is_new': True}, {'rate': '8.3', 'cover_x': 1429, 'title': '龙岭迷窟', 'url': 'https://movie.douban.com/subject/30488569/', 'playable': True, 'cover': 'https://img9.doubanio.com/view/photo/s_ratio_poster/public/p2593664928.jpg', 'id': '30488569', 'cover_y': 2000, 'is_new': False}, {'rate': '8.5', 'cover_x': 2100, 'title': '极地暗杀 第一季', 'url': 'https://movie.douban.com/subject/30466455/', 'playable': False, 'cover': 'https://img9.doubanio.com/view/photo/s_ratio_poster/public/p2608896785.jpg', 'id': '30466455', 'cover_y': 3000, 'is_new': False}, {'rate': '8.8', 'cover_x': 540, 'title': '了解的不多也无妨，是一家人', 'url': 'https://movie.douban.com/subject/34965662/', 'playable': False, 'cover': 'https://img9.doubanio.com/view/photo/s_ratio_poster/public/p2596104860.jpg', 'id': '34965662', 'cover_y': 763, 'is_new': False}, {'rate': '7.3', 'cover_x': 1242, 'title': '拜托了冰箱 第六季', 'url': 'https://movie.douban.com/subject/34431574/', 'playable': True, 'cover': 'https://img9.doubanio.com/view/photo/s_ratio_poster/public/p2598468290.jpg', 'id': '34431574', 'cover_y': 2208, 'is_new': False}, {'rate': '9.1', 'cover_x': 1005, 'title': '365：逆转命运的1年', 'url': 'https://movie.douban.com/subject/34902595/', 'playable': False, 'cover': 'https://img9.doubanio.com/view/photo/s_ratio_poster/public/p2589342098.jpg', 'id': '34902595', 'cover_y': 1440, 'is_new': False}, {'rate': '9.5', 'cover_x': 1204, 'title': '我们与恶的距离', 'url': 'https://movie.douban.com/subject/30181230/', 'playable': True, 'cover': 'https://img9.doubanio.com/view/photo/s_ratio_poster/public/p2554916825.jpg', 'id': '30181230', 'cover_y': 1720, 'is_new': False}, {'rate': '7.2', 'cover_x': 680, 'title': '国王：永远的君主', 'url': 'https://movie.douban.com/subject/33437305/', 'playable': False, 'cover': 'https://img9.doubanio.com/view/photo/s_ratio_poster/public/p2596184412.jpg', 'id': '33437305', 'cover_y': 1000, 'is_new': False}, {'rate': '6.2', 'cover_x': 1406, 'title': '奔跑吧 第四季', 'url': 'https://movie.douban.com/subject/35023699/', 'playable': True, 'cover': 'https://img9.doubanio.com/view/photo/s_ratio_poster/public/p2604118213.jpg', 'id': '35023699', 'cover_y': 2500, 'is_new': False}, {'rate': '9.4', 'cover_x': 400, 'title': '非自然死亡', 'url': 'https://movie.douban.com/subject/27140017/', 'playable': True, 'cover': 'https://img9.doubanio.com/view/photo/s_ratio_poster/public/p2510604929.jpg', 'id': '27140017', 'cover_y': 600, 'is_new': False}]

In [54]:
name=[]
score=[]
pnumber=[]
url=[]
cover=[]
id=[]
for one in html1:
    name.append(one['title'])
    score.append(one['rate'])
    pnumber.append(one['cover_y'])
    url.append(one['url'])
    cover.append(one['cover'])
    id.append(one['id'])
print(url)

['https://movie.douban.com/subject/34861173/', 'https://movie.douban.com/subject/30299248/', 'https://movie.douban.com/subject/33475999/', 'https://movie.douban.com/subject/35099748/', 'https://movie.douban.com/subject/35000628/', 'https://movie.douban.com/subject/26302614/', 'https://movie.douban.com/subject/34880852/', 'https://movie.douban.com/subject/34951001/', 'https://movie.douban.com/subject/34814172/', 'https://movie.douban.com/subject/30468961/', 'https://movie.douban.com/subject/35049287/', 'https://movie.douban.com/subject/30488569/', 'https://movie.douban.com/subject/30466455/', 'https://movie.douban.com/subject/34965662/', 'https://movie.douban.com/subject/34431574/', 'https://movie.douban.com/subject/34902595/', 'https://movie.douban.com/subject/30181230/', 'https://movie.douban.com/subject/33437305/', 'https://movie.douban.com/subject/35023699/', 'https://movie.douban.com/subject/27140017/']

In [55]:
columns={'剧名':name,'评分':score,'点评数':pnumber,'url':url,'图片':cover,'id':id}
data=pd.DataFrame(columns)

In [56]:
title=[]
jianj=[]
juqing=[]
otherlike=[]
biaoqian=[]
watch=[]

for i in range(len(data['url'])):
    res=requests.get(data['url'][i],headers=headers,cookies=cookie)
    html = etree.HTML(res.text)
    title.append(''.join(html.xpath('//div[@class="sub-title"]/text()')))
    jianj.append(''.join(html.xpath('//*[@id="link-report"]//span[@property="v:summary"]/text()')))
    juqing.append(''.join(html.xpath('//div[@class="bd"]/p/text()')))
    otherlike.append(''.join(html.xpath('//div[@class="wp"]/h3/text()')))
    biaoqian.append(''.join(html.xpath('//div[@class="con remark"]/a/text()')))
    watch.append(''.join(html.xpath('//span[@class="vendor-text"]/text()')))

In [24]:
columns={'剧名':title,'简介':jianj,'剧情':juqing,'还喜欢':otherlike,'标签':biaoqian,'观看':watch}
df2=pd.DataFrame(columns)
df2.head()

,剧名,简介,剧情,还喜欢,标签,观看
0,向往的生活 第四季,\n \n 中国大陆 / 真人秀 / 2020-05-08(...,\n 黄磊、何炅、彭昱畅和张子枫四位成员，来到了云南西双版纳。蘑菇屋的四位成员...,拜托了冰箱 第六季向往的生活 第一季乘风破浪的姐姐拜托了冰箱 第一季声临其境 第一季中央广播...,,\n 即将可播\n
1,杀手,\n \n 中国香港 / 剧情 / 犯罪 / 2020-06...,\n 乔星（陈豪饰）、阎武（黎耀祥饰），一个是如日中天的神级杀手，一个是风光不...,反黑路人甲街坊财爷夸世代三个女人一个「因」过街英雄盲侠大律师战毒是咁的，法官阁下毕打自己人男亲女爱,,\n 可在线观看\n
2,99分女朋友,\n \n 中国大陆 / 爱情 / 2020-06-17(中...,\n 颜即正义？化妆就是金手指！身患幻想症脸上有疤的化妆师孟醒，竟从史上最抠总...,我不是购物狂手可摘星辰亲爱的义祁君全世界最好的你奈何BOSS又如何欢乐喜剧人 第六季萌医甜妻...,,\n 即将可播\n
3,寻味东莞,\n \n 中国大陆 / 纪录片 / 2020-06-21(...,\n 东莞，中国广东重要的交通枢纽和外贸口岸，中国最具活力的国际化城市之一。过...,辣子曰风味人间 第二季小孩的神秘生活我的白大褂中间人生江湖菜馆社火中国年早餐中国 第二季寻味...,,\n 可在线观看\n
4,Life 线上的我们,\n \n 日本 / 剧情 / 同性 / 2020-06-1...,\n 讲述了坠入爱河的性格截然不同的两名男高中生，一边纠结一边走完人生的故事。,你的目光所及之处千星传说爱你，维克托越界你是我的氧气红色气球我们的天空是非靛蓝色的心情深蓝之吻,,\n 即将可播\n

In [49]:
jianj = []
for i in range(len(data['url'])):
    res=requests.get(data['url'][i],headers=headers,cookies=cookie)
    html = etree.HTML(res.text)
    jianj.append(''.join(html.xpath('//div[@class="sub-meta"]/text()')))

AttributeError: 'NoneType' object has no attribute 'xpath'

In [48]:
html1.xpath('//*[@id="link-report"]/span/text()')

AttributeError: 'list' object has no attribute 'xpath'

In [46]:
jianj

['',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '']

备注：这里需要注意的是：‘加载更多’这个需要更换参数params，需要查看xhr;同时，网址url需要重新构造

## 三、整合

### 1、构造请求部分

In [18]:
#headers、cookies
headers={'User-Agent':'Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Mobile Safari/537.36'}
b='bid="Q+TyquofF3k"; __gads=ID=27c34c24591f68b8:T=1583826922:S=ALNI_MYTBT08_oTj8FoP0Ub_rIKIeR_gkg; __utmc=30149280; __utmz=30149280.1583826934.1.1.utmcsr=baidu|utmccn=(organic)|utmcmd=organic; _vwo_uuid_v2=D38A74B855BBE6DEEA011650D499503FA|724b25b8fa8f857bd49036a32f21b010; ll="118371"; ap_v=0,6.0; gr_user_id=cde4f6c4-366d-446d-bbdb-7a91208d4dfc; __utma=30149280.426755224.1583826934.1583826934.1583934927.2; _pk_ref.100001.4cf6=%5B%22%22%2C%22%22%2C1583934928%2C%22https%3A%2F%2Fwww.baidu.com%2Fs%3Fie%3DUTF-8%26wd%3D%25E8%25B1%2586%25E7%2593%25A3%22%5D; _pk_ses.100001.4cf6=*; __utma=223695111.937284787.1583934929.1583934929.1583934929.1; __utmb=223695111.0.10.1583934929; __utmc=223695111; __utmz=223695111.1583934929.1.1.utmcsr=baidu|utmccn=(organic)|utmcmd=organic|utmctr=%E8%B1%86%E7%93%A3; __yadk_uid=ZCiNH3mBQOmatFURzBilWB3ZG7CcNAlS; push_noty_num=0; push_doumail_num=0; dbcl2="164789361:tRUWWY3I3X8"; ck=m_O9; __utmt=1; __utmv=30149280.16478; __utmb=30149280.3.10.1583934927; _pk_id.100001.4cf6=0cfb4938b254bf7c.1583934928.1.1583937455.1583934928.'
line=b.split(';')
cookie={}
for i in line:
    key,value = i.split('=',1)
    cookie[key] = value

In [19]:
titleall=[]
jianjall=[]
juqingall=[]
otherlikeall=[]
biaoqianall=[]
watchall=[]

In [101]:
#for j in range(len(data['url'])):
#    res=requests.get(data['url'][j],headers=headers,cookies=cookie)
#    html2 = etree.HTML(res.text)
#    titleall.append(''.join(html2.xpath('//div[@class="sub-title"]/text()')))
#    jianjall.append(''.join(html2.xpath('//div[@class="sub-meta"]/text()')))
#    juqingall.append(''.join(html2.xpath('//div[@class="bd"]/p/text()')))
#    otherlikeall.append(''.join(html2.xpath('//div[@class="wp"]/h3/text()')))
#    biaoqianall.append(''.join(html2.xpath('//div[@class="con remark"]/a/text()')))
#    watchall.append(''.join(html2.xpath('//span[@class="vendor-text"]/text()')))

In [20]:
#构造url和
for i in range(25):
    offset=i*20
    url='https://movie.douban.com/j/search_subjects?type=tv&tag=%E7%83%AD%E9%97%A8&sort=recommend&page_limit=20&page_start='+str(offset)          
    d = {
    'type': 'tv',
    'tag': '热门',
    'page_limit': 20,
    'page_start': offset
    }
    response=requests.get(url,headers=headers,cookies=cookie,params=d)
    response.encoding = 'utf-8'
    html = response.json()  # 将json格式的字符串转为python数据类型
    html1=html['subjects']
    #一页的内容获取，此处只用urls
    name=[]
    score=[]
    pnumber=[]
    urls=[]
    cover=[]
    id=[]
    for one in html1:
        name.append(one['title'])
        score.append(one['rate'])
        pnumber.append(one['cover_y'])
        urls.append(one['url'])
        cover.append(one['cover'])
        id.append(one['id'])
    #print(urls)
    columns={'剧名':name,'评分':score,'点评数':pnumber,'url':urls,'图片':cover,'id':id}
    data=pd.DataFrame(columns)
    #内部信息
    for i in range(len(data['url'])):
        res=requests.get(data['url'][i],headers=headers,cookies=cookie)
        html2 = etree.HTML(res.text)
        titleall.append(''.join(html2.xpath('//div[@class="sub-title"]/text()')))
        jianjall.append(''.join(html2.xpath('//div[@class="sub-meta"]/text()')))
        juqingall.append(''.join(html2.xpath('//div[@class="bd"]/p/text()')))
        otherlikeall.append(''.join(html2.xpath('//div[@class="wp"]/h3/text()')))
        biaoqianall.append(''.join(html2.xpath('//div[@class="con remark"]/a/text()')))
        watchall.append(''.join(html2.xpath('//span[@class="vendor-text"]/text()')))

ProxyError: HTTPSConnectionPool(host='m.douban.com', port=443): Max retries exceeded with url: /movie/subject/27195020/ (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')))

In [ ]:
len(titleall)

In [31]:
columns={'剧名':titleall,'简介':jianjall,'剧情':juqingall,'还喜欢':otherlikeall,'标签':biaoqianall,'观看':watchall}
df2=pd.DataFrame(columns)
df2.head()

,剧名,简介,剧情,还喜欢,标签,观看
0,龙岭迷窟,\n \n 中国大陆 / 剧情 / 动作 / 冒险 / 20...,\n 胡八一、王胖子和大金牙被村民编造的绣花鞋的故事所骗，前往陕西古蓝县。水路...,怒晴湘西云南虫谷鬼吹灯之精绝古城白夜追凶河神龙岭迷窟之最后的搬山道人唐人街探案局中人伪装者无证之罪,,\n 可在线观看\n
1,风味人间 第二季,\n \n 中国大陆 / 纪录片 / 2020-04-26(...,\n 因为地理环境、文明历程和物产丰厚程度不尽相同，人们对食物的处理时而天差地...,风味人间 第一季早餐中国 第二季人生一串 第二季电子竞技在中国寻味顺德小孩的神秘生活我的白大...,,\n 可在线观看\n
2,降魔的2.0,\n \n 中国香港 / 剧情 / 悬疑 / 2020-05...,\n 的士司机马季（马国明饰）继承精灵石敢当的天命，走上降魔之路，更与长大的好...,十八年后的终极告白食梦先生失踪人口也平凡爱思小姐探案集局中人古董局中局之鉴墨寻瓷完美证据降魔...,,\n 可在线观看\n
3,绝夜逢生,\n \n 比利时 / 剧情 / 科幻 / 惊悚 / 202...,\n 讲述一架在布鲁塞尔的航班起飞后，此时太阳活动突变令到被照射到的生物通通死...,3% 第一季沙丘：姐妹会上载新生救世 第一季环形物语雪国列车(剧版) 第一季再次钟情 第一季...,,\n 即将可播\n
4,低俗怪谈：天使之城,\n \n 美国 / 剧情 / 恐怖 / 2020-04-2...,\n 故事将离开维多利亚时代的伦 敦，改为以新角色及新故事讲述1938年的洛杉...,惊悚50州低俗怪谈 第三季我知道你去年夏天干了什么鬼入侵 第二季时光之轮恶灵玛丽安恶魔之地女...,,\n 即将可播\n