## 实战项目-前程无忧网站招聘数据获取

### 一、目标网站

### <img src="图1.png">

### 二、项目目标

#### 获取目前数据分析师职位招聘市场的招聘数据，以此进行岗位薪资的分析，不仅能为高校的人才培养方案的制定进行策略建议，还能了解学生薪资情况！时刻把握市场动态！

### <img src="图2.png">

### <img src="图3.png">

### 三、爬取任务分解

### 总体分析任务：一页爬取——多页爬取

#### （一）一页数据爬取

In [1]:
import requests
from lxml import etree
import pandas as pd

In [2]:
#防止数据量大时候出现SSL验证报错
import cryptography
import certifi
from OpenSSL import SSL

In [4]:
#设置headers
headers={'User-Agent': 'Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Mobile Safari/537.36'}

In [6]:
#设置cookie
b='adv=adsnew%3D1%26%7C%26adsresume%3D1%26%7C%26adsfrom%3Dhttps%253A%252F%252Fwww.baidu.com%252Fbaidu.php%253Fsc.Ks00000EAMrnlPLIybYNddmhQxV6IThZIe70Sr8VGpPGAfEzIiBE3N8p4LE2LEWCAHyzBdESmMZ-sGbi0sHVd6dhuzz4rfykOQ6N80T4NJgVb2RtQINK4AnOhKIekZ45BUl7eB4IbpXpwye5vkWgttCVOuz2P80--SJceSvd9MaxBTyepp5o5WQo-14LrX_R3tZ_9JO3m-wU6DsC4Er88NrA9MDF.7R_NR2Ar5Od66CHnsGtVdXNdlc2D1n2xx81IZ76Y_u2qS1x3dqyT8P9MqOOgujSOODlxdlPqKMWSxKSgqjlSzOFqtZOmzUlZlS5S8QqxZtVAOtItISiel5SKkOeZwSEHNuxSLsfxzcEqolQOY2LOqWq8WvLxVOgVlqoAzAVPBxZub88zuQCUS1FIEtR_4n-LiMGePOBGyAp7WFEePl6.U1Y10ZDqdIjA80Kspynqn0KsTv-MUWY1njNBujuhnvwBm17BnvcLmyD1mhRYnvubuW01PvDdnsKY5IgfkoBe3fKGUHYznWR0u1dEuZCk0ZNG5yF9pywd0ZKGujYzPsKWpyfqnWfY0AdY5HDsnH-xnH0kPdtznjmzg1Dknjfkg1nsnjuxn1msnfKopHYs0ZFY5HD3P6K-pyfqn104P1KxnHfdnNtznHDkndt1nj6Yn7t1njb4PNt1nj6zndt1njTkPsKBpHYkPH9xnW0Yg1ckPsKVm1Yknj0kg1D3Pjbknjm4rHNxrHczn1T3PWm3P-tYn7tknjFxn0KkTA-b5H00TyPGujYs0ZFMIA7M5H00mycqn7ts0ANzu1Ys0ZKs5H00UMus5H08nj0snj0snj00Ugws5H00uAwETjYs0ZFJ5H00uANv5gKW0AuY5H00TA6qn0KET1Ys0AFL5HDs0A4Y5H00TLCq0A71gv-bm1dsTzdMXh93XfKGuAnqiD4K0ZwdT1Ykn1f3nHbvrjTsPWD1PW6Lnjmvn6Kzug7Y5HDdrjnvPjDYrHD3nHf0Tv-b5yPBPH63ujuBnj0sPjT3Pvf0mLPV5HbvPjPDwWIjnYuarHIjnWb0mynqnfKYIgfqnfKsUWYs0Z7VIjYs0Z7VT1Ys0ZGY5H00UyPxuMFEUHYsg1Kxn7tsg1nsnH7xn0Kbmy4dmhNxTAk9Uh-bT1Ysg1Kxn7tznjRznHKxPjc1PjnvnNts0ZK9I7qhUA7M5H00uAPGujYs0ANYpyfqQHD0mgPsmvnqn0KdTA-8mvnqn0KkUymqn0KhmLNY5H00pgPWUjYs0ZGsUZN15H00mywhUA7M5H60UAuW5H00uAPWujY0mhwGujdKPjIjfH-AP1DdwjwDwRcYn1uDPRPafbFAPj0kPWPDwfKBIjYs0AqY5H00ULFsIjYsc10Wc10Wnansc108nj0snj0sc10Wc100TNqv5H08rH9xna3sn7tsQW0sg108nWIxna3sPdtsQWnY0AN3IjYs0APzm1YzPHDkn6%2526word%253D%2525E6%25258B%25259B%2525E8%252581%252598%2526ck%253D2539.10.112.366.290.220.175.400%2526shh%253Dwww.baidu.com%2526us%253D1.26594.3.0.2.929.0%2526bc%253D110101%26%7C%26adsnum%3D2198971; guid=<YOUR_GUID>; partner=www_baidu_com; nsearch=jobarea%3D%26%7C%26ord_field%3D%26%7C%26recentSearch0%3D%26%7C%26recentSearch1%3D%26%7C%26recentSearch2%3D%26%7C%26recentSearch3%3D%26%7C%26recentSearch4%3D%26%7C%26collapse_expansion%3D; search=jobarea%7E%60000000%7C%21ord_field%7E%600%7C%21recentSearch0%7E%60000000%A1%FB%A1%FA000000%A1%FB%A1%FA0000%A1%FB%A1%FA00%A1%FB%A1%FA99%A1%FB%A1%FA%A1%FB%A1%FA99%A1%FB%A1%FA99%A1%FB%A1%FA99%A1%FB%A1%FA99%A1%FB%A1%FA9%A1%FB%A1%FA99%A1%FB%A1%FA%A1%FB%A1%FA0%A1%FB%A1%FA%D0%C2%C3%BD%CC%E5%C4%DA%C8%DD%D4%CB%D3%AA%A1%FB%A1%FA2%A1%FB%A1%FA1%7C%21recentSearch1%7E%60200200%A1%FB%A1%FA000000%A1%FB%A1%FA0000%A1%FB%A1%FA00%A1%FB%A1%FA99%A1%FB%A1%FA%A1%FB%A1%FA99%A1%FB%A1%FA99%A1%FB%A1%FA99%A1%FB%A1%FA99%A1%FB%A1%FA9%A1%FB%A1%FA99%A1%FB%A1%FA%A1%FB%A1%FA0%A1%FB%A1%FA%C3%BD%CC%E5%CA%FD%BE%DD%B7%D6%CE%F6%A1%FB%A1%FA2%A1%FB%A1%FA1%7C%21; m_search=keyword%3D%E6%96%B0%E5%AA%92%E4%BD%93%E5%86%85%E5%AE%B9%E8%BF%90%E8%90%A5%26%7C%26areacode%3D000000'
line=b.split(';')
cookie={}
for i in line:
    key,value = i.split('=',1)
    cookie[key] = value

In [ ]:

https://m.51job.com/search/joblist.php?keyword=%E6%95%B0%E6%8D%AE%E5%88%86%E6%9E%90%E5%B8%88&keywordtype=2&funtype=0000&indtype=00&jobarea=000000&jobterm=99&cotype=99&issuedate=9&saltype=99&degree=99&landmark=0&workyear=99&cosize=99&radius=-1&lonlat=0%2C0

In [6]:
#观察页面URL的变化

In [ ]:
#page1

In [ ]:
https://m.51job.com/search/joblist.php?jobarea=000000&keyword=%E6%95%B0%E6%8D%AE%E5%88%86%E6%9E%90%E5%B8%88&keywordtype=2&pageno=1

In [ ]:
#page2

In [ ]:
#page1
https://m.51job.com/search/joblist.php?jobarea=000000&keyword=%E6%95%B0%E6%8D%AE%E5%88%86%E6%9E%90%E5%B8%88&keywordtype=2&pageno=2

#### 问题1—keyword为啥是乱码？

In [ ]:
#对于URL的再次改造

In [ ]:
https://m.51job.com/search/joblist.php?jobarea=000000&keyword=数据分析师&keywordtype=2&pageno=1

### <img src="图4.png">

In [8]:
#计算该关键词对应的页数
i=0
url0='https://m.51job.com/search/joblist.php?jobarea=000000&keyword=数据分析师&keywordtype=2&pageno=1'
res0=requests.get(url0,headers=headers,cookies=cookie)
res0.encoding='utf-8'
re0=res0.text
html0 = etree.HTML(re0)
page=html0.xpath('//div[@class="paging"]/span[@class="bb"]/font/select/option/text()')

In [9]:
page

['1',
 '2',
 '3',
 '4',
 '5',
 '6',
 '7',
 '8',
 '9',
 '10',
 '11',
 '12',
 '13',
 '14',
 '15',
 '16',
 '17',
 '18',
 '19',
 '20',
 '21',
 '22',
 '23',
 '24',
 '25',
 '26',
 '27',
 '28',
 '29',
 '30',
 '31',
 '32',
 '33',
 '34',
 '35',
 '36',
 '37',
 '38',
 '39',
 '40',
 '41',
 '42',
 '43',
 '44',
 '45',
 '46',
 '47',
 '48',
 '49',
 '50',
 '51']

In [7]:
url_son=html0.xpath('//div[@class="items"]/a/@href')

In [9]:
gang = []
didian = []
time = []
money = []
people = []
name = []
xingz = []
dizhi = []
describe = []
work = []
renz = []

In [10]:
for i in range(len(url_son)):
    res_son=requests.get(url_son[i],headers=headers)
    res_son.encoding='utf-8'
    html_son = etree.HTML(res_son.text)
    gang.append(html_son.xpath('//div[@class="jt"]/p/text()'))
    didian.append(html_son.xpath('//div[@class="jt"]/em/text()'))
    time.append(html_son.xpath('//div[@class="jt"]/span/text()'))
    money.append(html_son.xpath('//p[@class="jp"]/text()'))
    people.append(html_son.xpath('//div[@class="jd"]/span/text()'))
    name.append(html_son.xpath('//div[@class="rec"]/a/p[@class="c_444"]/text()'))
    xingz.append(html_son.xpath('//div[@class="rec"]/a/div[@class="at"]/text()'))
    dizhi.append(html_son.xpath('//div[@class="rec"]/a/span/text()'))
    describe.append(''.join(html_son.xpath('//div[@class="welfare"]/span/text()')))
    work.append(''.join(html_son.xpath('//div[@class="ain"]/article/p/text()')))
    renz.append(''.join(html_son.xpath('//div[@class="ain"]/article/p/text()')))

In [11]:
columns={'岗位':gang,'地点':didian,'时间':time,'薪资':money,'人数':people,'公司名':name,'公司性质':xingz,'公司地址':dizhi,'职位描述':describe,'职责描述':work}
df_onepage=pd.DataFrame(columns)

In [12]:
df_onepage.head()

,岗位,地点,时间,薪资,人数,公司名,公司性质,公司地址,职位描述,职责描述
0,[阿里文娱互动娱乐事业部-高级数据分析师-WY],[广州],[2020-06-11],[],"[若干人, 3-4年经验, 本科]",[阿里巴巴集团],[上市公司 | 10000人以上 | 互联网/电子商务],[],,
1,[数据分析师],[上海-浦东新区],[2020-06-11],[],"[1人, 2年经验]",[“前程无忧”51job.com（上海）],[外资（非欧美） | 1000-5000人 | 互联网/电子商务 专业服务(咨询、人力资源、...,[上班地址 : 张东路1387号3号楼],五险一金补充医疗保险专业培训定期体检,岗位职责： 1、运用数据挖掘/统计学习的理论和方法，深入挖掘和分析用户行为、业务数据； 2、...
2,[初级数据分析师-武汉-07268],[武汉],[2020-06-11],[5-6千/月],"[1人, 1年经验, 本科]",[武汉佰钧成技术有限责任公司],[民营公司 | 10000人以上 | 计算机软件 计算机服务(系统、数据服务、维修)],[上班地址 : 武汉市光谷软件园F1栋12楼],五险一金补充医疗保险弹性工作绩效奖金定期体检,职位描述：1、参与调研数据需求，建立数据分析框架体系，输出数据分析报告、建模报告、数据报表等...
3,[金融数据分析师],[北京-朝阳区],[2020-06-11],[1-1.5万/月],"[3人, 2年经验, 大专]",[北京融汇天诚投资管理有限公司],[合资 | 500-1000人 | 金融/投资/证券 贸易/进出口],[上班地址 : 北京市朝阳区朝外SOHO B座1020],,我们的要求——勤奋、好学；有很强的执行力、自制力、纪律性；有较强的抗压能力、学习能力、新知识...
4,[数据分析师-Tableau],[北京-朝阳区],[2020-06-11],[0.8-1.5万/月],"[若干人, 2年经验]",[深圳市优阅达数据科技有限公司上海分公司],[民营公司 | 50-150人 | 计算机服务(系统、数据服务、维修)],[上班地址 : 建国路华贸商务楼15号楼一层],五险一金交通补贴专业培训年终奖金定期体检,将要做什么↓

#### （二）多页数据爬取

##### 1、构造多页URL

In [13]:
url_list=[]

In [14]:
for i in range(len(page)):
    url_list.append('https://m.51job.com/search/joblist.php?jobarea=000000&keyword=数据分析师&&keywordtype=2&pageno='+str(i))

In [15]:
url_list

['https://m.51job.com/search/joblist.php?jobarea=000000&keyword=数据分析师&&keywordtype=2&pageno=0',
 'https://m.51job.com/search/joblist.php?jobarea=000000&keyword=数据分析师&&keywordtype=2&pageno=1',
 'https://m.51job.com/search/joblist.php?jobarea=000000&keyword=数据分析师&&keywordtype=2&pageno=2',
 'https://m.51job.com/search/joblist.php?jobarea=000000&keyword=数据分析师&&keywordtype=2&pageno=3',
 'https://m.51job.com/search/joblist.php?jobarea=000000&keyword=数据分析师&&keywordtype=2&pageno=4',
 'https://m.51job.com/search/joblist.php?jobarea=000000&keyword=数据分析师&&keywordtype=2&pageno=5',
 'https://m.51job.com/search/joblist.php?jobarea=000000&keyword=数据分析师&&keywordtype=2&pageno=6',
 'https://m.51job.com/search/joblist.php?jobarea=000000&keyword=数据分析师&&keywordtype=2&pageno=7',
 'https://m.51job.com/search/joblist.php?jobarea=000000&keyword=数据分析师&&keywordtype=2&pageno=8',
 'https://m.51job.com/search/joblist.php?jobarea=000000&keyword=数据分析师&&keywordtype=2&pageno=9',
 'https://m.51job.com/search/joblist.php?jobarea=000000&keyword=数据分析师&&keywordtype=2&pageno=10',
 'https://m.51job.com/search/joblist.php?jobarea=000000&keyword=数据分析师&&keywordtype=2&pageno=11',
 'https://m.51job.com/search/joblist.php?jobarea=000000&keyword=数据分析师&&keywordtype=2&pageno=12',
 'https://m.51job.com/search/joblist.php?jobarea=000000&keyword=数据分析师&&keywordtype=2&pageno=13',
 'https://m.51job.com/search/joblist.php?jobarea=000000&keyword=数据分析师&&keywordtype=2&pageno=14',
 'https://m.51job.com/search/joblist.php?jobarea=000000&keyword=数据分析师&&keywordtype=2&pageno=15',
 'https://m.51job.com/search/joblist.php?jobarea=000000&keyword=数据分析师&&keywordtype=2&pageno=16',
 'https://m.51job.com/search/joblist.php?jobarea=000000&keyword=数据分析师&&keywordtype=2&pageno=17',
 'https://m.51job.com/search/joblist.php?jobarea=000000&keyword=数据分析师&&keywordtype=2&pageno=18',
 'https://m.51job.com/search/joblist.php?jobarea=000000&keyword=数据分析师&&keywordtype=2&pageno=19',
 'https://m.51job.com/search/joblist.php?jobarea=000000&keyword=数据分析师&&keywordtype=2&pageno=20',
 'https://m.51job.com/search/joblist.php?jobarea=000000&keyword=数据分析师&&keywordtype=2&pageno=21',
 'https://m.51job.com/search/joblist.php?jobarea=000000&keyword=数据分析师&&keywordtype=2&pageno=22',
 'https://m.51job.com/search/joblist.php?jobarea=000000&keyword=数据分析师&&keywordtype=2&pageno=23',
 'https://m.51job.com/search/joblist.php?jobarea=000000&keyword=数据分析师&&keywordtype=2&pageno=24',
 'https://m.51job.com/search/joblist.php?jobarea=000000&keyword=数据分析师&&keywordtype=2&pageno=25',
 'https://m.51job.com/search/joblist.php?jobarea=000000&keyword=数据分析师&&keywordtype=2&pageno=26',
 'https://m.51job.com/search/joblist.php?jobarea=000000&keyword=数据分析师&&keywordtype=2&pageno=27',
 'https://m.51job.com/search/joblist.php?jobarea=000000&keyword=数据分析师&&keywordtype=2&pageno=28',
 'https://m.51job.com/search/joblist.php?jobarea=000000&keyword=数据分析师&&keywordtype=2&pageno=29',
 'https://m.51job.com/search/joblist.php?jobarea=000000&keyword=数据分析师&&keywordtype=2&pageno=30',
 'https://m.51job.com/search/joblist.php?jobarea=000000&keyword=数据分析师&&keywordtype=2&pageno=31',
 'https://m.51job.com/search/joblist.php?jobarea=000000&keyword=数据分析师&&keywordtype=2&pageno=32',
 'https://m.51job.com/search/joblist.php?jobarea=000000&keyword=数据分析师&&keywordtype=2&pageno=33',
 'https://m.51job.com/search/joblist.php?jobarea=000000&keyword=数据分析师&&keywordtype=2&pageno=34',
 'https://m.51job.com/search/joblist.php?jobarea=000000&keyword=数据分析师&&keywordtype=2&pageno=35',
 'https://m.51job.com/search/joblist.php?jobarea=000000&keyword=数据分析师&&keywordtype=2&pageno=36',
 'https://m.51job.com/search/joblist.php?jobarea=000000&keyword=数据分析师&&keywordtype=2&pageno=37',
 'https://m.51job.com/search/joblist.php?jobarea=000000&keyword=数据分析师&&keywordtype=2&pageno=38',
 'https://m.51job.com/search/joblist.php?jobarea=000000&keyword=数据分析师&&keywordtype=2&pageno=39',
 'https://m.51job.com/search/joblist.php?jobarea=000000&keyword=数据分析师&&keywordtype=2&pageno=40',
 'https://m.51job.com/search/joblist.php?jobarea=000000&keyword=数据分析师&&keywordtype=2&pageno=41',
 'https://m.51job.com/search/joblist.php?jobarea=000000&keyword=数据分析师&&keywordtype=2&pageno=42',
 'https://m.51job.com/search/joblist.php?jobarea=000000&keyword=数据分析师&&keywordtype=2&pageno=43',
 'https://m.51job.com/search/joblist.php?jobarea=000000&keyword=数据分析师&&keywordtype=2&pageno=44',
 'https://m.51job.com/search/joblist.php?jobarea=000000&keyword=数据分析师&&keywordtype=2&pageno=45',
 'https://m.51job.com/search/joblist.php?jobarea=000000&keyword=数据分析师&&keywordtype=2&pageno=46',
 'https://m.51job.com/search/joblist.php?jobarea=000000&keyword=数据分析师&&keywordtype=2&pageno=47',
 'https://m.51job.com/search/joblist.php?jobarea=000000&keyword=数据分析师&&keywordtype=2&pageno=48',
 'https://m.51job.com/search/joblist.php?jobarea=000000&keyword=数据分析师&&keywordtype=2&pageno=49',
 'https://m.51job.com/search/joblist.php?jobarea=000000&keyword=数据分析师&&keywordtype=2&pageno=50']

In [7]:

#该关键词爬取
gang=[]#岗位
didian=[]#地点
time=[]#时间
money=[]#薪资
people=[]#人数
name=[]#公司名
xingz=[]#性质
dizhi=[]#地址
describe=[]#职位描述
work=[]#职责描述
renz=[]#任职要求

#页面计算
i=0
url0='https://m.51job.com/search/joblist.php?jobarea=000000&keyword=数据分析师&&keywordtype=2&pageno=1'
res0=requests.get(url0,headers=headers,cookies=cookie)
res0.encoding='utf-8'
re0=res0.text
html0 = etree.HTML(re0)
page=html0.xpath('//div[@class="paging"]/span[@class="bb"]/font/select/option/text()')

#爬取
for i in range(len(page)):
    url='https://m.51job.com/search/joblist.php?jobarea=000000&keyword=数据分析师&&keywordtype=2&pageno='+str(i)
    res=requests.get(url,headers=headers,cookies=cookie)
    res.encoding='utf-8'
    re=res.text
    html = etree.HTML(re)
    url_son=html.xpath('//div[@class="items"]/a/@href') 
    for i in range(len(url_son)):
        res_son=requests.get(url_son[i],headers=headers)
        res_son.encoding='utf-8'
        html_son = etree.HTML(res_son.text)
        gang.append(html_son.xpath('//div[@class="jt"]/p/text()'))
        didian.append(html_son.xpath('//div[@class="jt"]/em/text()'))
        time.append(html_son.xpath('//div[@class="jt"]/span/text()'))
        money.append(html_son.xpath('//p[@class="jp"]/text()'))
        people.append(html_son.xpath('//div[@class="jd"]/span/text()'))
        name.append(html_son.xpath('//div[@class="rec"]/a/p[@class="c_444"]/text()'))
        xingz.append(html_son.xpath('//div[@class="rec"]/a/div[@class="at"]/text()'))
        dizhi.append(html_son.xpath('//div[@class="rec"]/a/span/text()'))
        describe.append(''.join(html_son.xpath('//div[@class="welfare"]/span/text()')))
        work.append(''.join(html_son.xpath('//div[@class="ain"]/article/p/text()')))
        renz.append(''.join(html_son.xpath('//div[@class="ain"]/article/p/text()')))

From cffi callback <function _verify_callback at 0x00000220256920D8>:
Traceback (most recent call last):
  File "E:\Anaconda3\lib\site-packages\OpenSSL\SSL.py", line 311, in wrapper
    @wraps(callback)
KeyboardInterrupt

SSLError: HTTPSConnectionPool(host='m.51job.com', port=443): Max retries exceeded with url: /jobs/shenzhen/122406430.html (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])")))

In [9]:
columns={'岗位':gang,'地点':didian,'时间':time,'薪资':money,'人数':people,'公司名':name,'公司性质':xingz,'公司地址':dizhi,'职位描述':describe,'职责描述':work}
df=pd.DataFrame(columns)

In [10]:
df.head()

,岗位,地点,时间,薪资,人数,公司名,公司性质,公司地址,职位描述,职责描述
0,[阿里文娱互动娱乐事业部-高级数据分析师-WY],[广州],[2020-06-11],[],"[若干人, 3-4年经验, 本科]",[阿里巴巴集团],[上市公司 | 10000人以上 | 互联网/电子商务],[],,
1,[数据分析师],[上海-浦东新区],[2020-06-11],[],"[1人, 2年经验]",[“前程无忧”51job.com（上海）],[外资（非欧美） | 1000-5000人 | 互联网/电子商务 专业服务(咨询、人力资源、...,[上班地址 : 张东路1387号3号楼],五险一金补充医疗保险专业培训定期体检,岗位职责： 1、运用数据挖掘/统计学习的理论和方法，深入挖掘和分析用户行为、业务数据； 2、...
2,[初级数据分析师-武汉-07268],[武汉],[2020-06-11],[5-6千/月],"[1人, 1年经验, 本科]",[武汉佰钧成技术有限责任公司],[民营公司 | 10000人以上 | 计算机软件 计算机服务(系统、数据服务、维修)],[上班地址 : 武汉市光谷软件园F1栋12楼],五险一金补充医疗保险弹性工作绩效奖金定期体检,职位描述：1、参与调研数据需求，建立数据分析框架体系，输出数据分析报告、建模报告、数据报表等...
3,[数据分析师主管],[北京-朝阳区],[2020-06-11],[2.5-3万/月],"[2人, 无需经验, 大专]",[东恒万通（北京）信息咨询服务有限公司],[合资 | 500-1000人 | 金融/投资/证券],[上班地址 : 朝阳区朝外SOHO B座1020],五险一金员工旅游绩效奖金弹性工作定期体检出国机会专业培训补充公积金通讯补贴,任职要求。1、热爱投资、对投资经济知识感兴趣。15152、有很强的执行力，自制力强，有风控意...
4,[金融数据分析师],[北京-朝阳区],[2020-06-11],[1-1.5万/月],"[3人, 2年经验, 大专]",[北京融汇天诚投资管理有限公司],[合资 | 500-1000人 | 金融/投资/证券 贸易/进出口],[上班地址 : 北京市朝阳区朝外SOHO B座1020],,我们的要求——勤奋、好学；有很强的执行力、自制力、纪律性；有较强的抗压能力、学习能力、新知识...

In [13]:
df['职责描述'][4]

'我们的要求——勤奋、好学；有很强的执行力、自制力、纪律性；有较强的抗压能力、学习能力、新知识的接受能力的有识之士。合格者可进入公司核心团队岗位职责：1、协助部门经理完善部门管理制度；2、协助分析师制定每日开的分析计划；3、协助分析师分析金融市场数据，为相关部门提供有价值的信息；4、金融市场的定向研究；任职要求：1、年龄：25-45岁，五官端正，性格开朗，善于沟通；2、为人诚实，具有责任心、上进心，较强的执行力。3、接受大学生在校实习、退伍军人与应届毕业生优先录取；4、具有良好的人品与职业操守，踏实、细致的工作作风；晋升空间：1、公司有广阔的晋升空间，薪资晋升、职位晋升；可纵向、横向晋升；2、公司会有相关制度上的考核，每季度可进行一次晋升考核；3、根据个人日常工作表现、\xa0工作能力、工作态度、执行能力、考勤制度而定01；预约手机号：13581514712同v'

In [14]:
df['删除'],df['任职要求']=df['职责描述'].str.split('任职要求：',1).str

In [15]:
data_finall=df.drop( ['删除'],axis=1)

In [17]:
data_finall.to_csv('数据分析师.csv',encoding='utf_8_sig')

In [11]:
#该关键词爬取
gang=[]#岗位
didian=[]#地点
time=[]#时间
money=[]#薪资
people=[]#人数
name=[]#公司名
xingz=[]#性质
dizhi=[]#地址
describe=[]#职位描述
work=[]#职责描述
renz=[]#任职要求

#页面计算
i=0
url0='https://m.51job.com/search/joblist.php?jobarea=000000&keyword=数据分析师&&keywordtype=2&pageno=1'
res0=requests.get(url0,headers=headers,cookies=cookie)
res0.encoding='utf-8'
re0=res0.text
html0 = etree.HTML(re0)
page=html0.xpath('//div[@class="paging"]/span[@class="bb"]/font/select/option/text()')

#爬取
for i in range(len(page[0:5])):
    url='https://m.51job.com/search/joblist.php?jobarea=000000&keyword=数据分析师&&keywordtype=2&pageno='+str(i)
    res=requests.get(url,headers=headers,cookies=cookie)
    res.encoding='utf-8'
    re=res.text
    html = etree.HTML(re)
    url_son=html.xpath('//div[@class="items"]/a/@href') 
    for i in range(len(url_son)):
        res_son=requests.get(url_son[i],headers=headers)
        res_son.encoding='utf-8'
        html_son = etree.HTML(res_son.text)
        gang.append(html_son.xpath('//div[@class="jt"]/p/text()'))
        didian.append(html_son.xpath('//div[@class="jt"]/em/text()'))
        time.append(html_son.xpath('//div[@class="jt"]/span/text()'))
        money.append(html_son.xpath('//p[@class="jp"]/text()'))
        people.append(html_son.xpath('//div[@class="jd"]/span/text()'))
        name.append(html_son.xpath('//div[@class="rec"]/a/p[@class="c_444"]/text()'))
        xingz.append(html_son.xpath('//div[@class="rec"]/a/div[@class="at"]/text()'))
        dizhi.append(html_son.xpath('//div[@class="rec"]/a/span/text()'))
        describe.append(''.join(html_son.xpath('//div[@class="welfare"]/span/text()')))
        work.append(''.join(html_son.xpath('//div[@class="ain"]/article/p/text()')))
        renz.append(''.join(html_son.xpath('//div[@class="ain"]/article/p/text()')))

ProxyError: HTTPSConnectionPool(host='msearch.51job.com', port=443): Max retries exceeded with url: /jobs/all/122823911.html?rc=03 (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')))